### ISSUE TITLE
Dictionary snapshots

### ISSUE THREAD

**Issue by luisrecuenco** [pointfreeco/swift-snapshot-testing#101]
Dictionary snapshotting is not deterministic. Let's consider the following snapshot.

```
let dictionary = ["first": 1, "second": 2, "third": 3]
assertSnapshot(matching: dictionary)
```

Each time the snapshot is made, the snapshot result is different.

```
▿ 3 key/value pairs
  ▿ (2 elements)
    - key: "third"
    - value: 3
  ▿ (2 elements)
    - key: "first"
    - value: 1
  ▿ (2 elements)
    - key: "second"
    - value: 2
```

```
▿ 3 key/value pairs
  ▿ (2 elements)
    - key: "first"
    - value: 1
  ▿ (2 elements)
    - key: "third"
    - value: 3
  ▿ (2 elements)
    - key: "second"
    - value: 2
```

Is there any way to handle this scenario correctly? Should we have a strategy for `Dictionary<Comparable, T>` so the snapshot is captured by sorting the keys in the first place?

Thanks

**Comment by stephencelis** [comment]
The `.dump` strategy should be able to deterministically sort things. I can try to cook up a fix later unless you wanna give it a shot! I'd be happy to point you in the right direction and answer any questions you have along the way.
