### ISSUE TITLE
How to conform to DefaultSnapshottable

### ISSUE THREAD

**Issue by loudmouth** [pointfreeco/swift-snapshot-testing#106]
Hey there,

First off, this library looks awesome and I really enjoyed reading the article you posted about it.

I was starting to integrate this into a project of mine and was intrigued by applying snapshots to instance of arbitrary types—this seems to be one advantage of this lib over FBSnapshotTestCase. I quickly found out that my types would need to conform to `DefaultSnapshottable` in order to assert snapshot matches for them. I'm fine implementing conformance via extensions in my test target, but I've yet to figure out the intent of the associated types and how I might implement conformance.

Let's say I wanted to test `NSAttributedString`, since in my case my library is rendering an NSAttributedString with a _lot_ of custom attributes. Any advice on how I would declare conformance to `DefaultSnapshottable` for `NSAttributedString`? Specifically, not sure what the associatedtype `Format` should be

**Comment by loudmouth** [comment]
After doing some digging, I realize that implementing conformance might be tricky, and not something I have time for at the moment. I think conformance for `NSAttributedString` would be sufficient for my own use-case and if #52 is to be seen as a feature roadmap, it looks like it will be done in the future. If #52 is the feature roadmap, feel free to close this issue

**Comment by mbrandonw** [comment]
> After doing some digging, I realize that implementing conformance might be tricky, and not something I have time for at the moment. I think conformance for `NSAttributedString` would be sufficient for my own use-case and if #52 is to be seen as a feature roadmap, it looks like it will be done in the future. If #52 is the feature roadmap, feel free to close this issue

Yeah attributed strings are definitely on our roadmap. The code I posted above is essentially what we'll be adding to the library, but right now we are heads down for the next week to get the 1.0 release of this library ready. We will get to it soon after that, or if you wanted to give it a shot that'd be great too!

**Comment by loudmouth** [comment]
Wowzas, thanks for the ultra-comprehensive response.

Since I'm rendering to an `NSAttributedString` with custom attributes, i.e. attributes that are not native, but implemented by me, it turns out that using the `.dump` strategy is perfect. It gives me the ability to snapshot all the attributes at each respective range of characters.

I'm going to close this for now, as this issue was more of a forum-style question/answer.

Keep up the good work with this lib and thanks for the help!

**Comment by mbrandonw** [comment]
@loudmouth that's great to hear! we would love to see how you end up using this if it's open source.

**Comment by loudmouth** [comment]
Well it is open-source ;-)

[here](https://github.com/contentful-labs/rich-text-renderer.swift/pull/4/files#diff-c9d29b12b3fd8bc588da5c78902ee373) is the test code from my PR.


and [here](https://github.com/contentful-labs/rich-text-renderer.swift/blob/4713c992d47bb72562386542ed1820ec93d91647/Example/RendererExampleTests/__Snapshots__/SnapshotTests/testComplexListSnapshot.1.png) is an example snapshot of a view.


Now, the one thing I don't understand is why my test target renders the view differently than when the view is rendered in the main target, but I think that issue is something to do with my heavy usage of [TextKit](https://developer.apple.com/documentation/appkit/textkit) and not your library

As a last sidenote, I have been a fan of [KIF](https://github.com/kif-framework/KIF) since I first found out about it and I think it pairs nicely with snapshot testing as you can easily "wait" until views with the relevant accessibility identifiers are displayed. You can see usage of that in my PR.

**Comment by AgapovOne** [comment]
Current possible way of adding snapshotting support for `NSAttributedString`:

```swift
extension Snapshotting where Value == NSAttributedString, Format == UIImage {
    public static var image: Snapshotting {
        Snapshotting<UIView, UIImage>.image.pullback { (attributedString: NSAttributedString) in
            let textView = UITextView()
            textView.attributedText = attributedString
            return textView
        }
    }
}

```
