### ISSUE TITLE
Timeouts on WKWebView image snapshot

### ISSUE THREAD

**Issue by kaqu** [pointfreeco/swift-snapshot-testing#126]
Hi, one more issue from me 😇 It looks like WKWebView is never performing image snapshot when there is no content loaded. I have the case where one of my views contains WKWebView that have no content initially. If I've debugged that correctly image snapshot on web view waits until the page finishes loading. But when there is no page loading it never occurs resulting in a timeout. 
I am wondering if making it possible to take a snapshot when there is no content in web view is a good solution here.
Workaround for this is to load any file from disk into, even empty one.

**Comment by stephencelis** [comment]
Ah, good point, embedded web views shouldn’t time out if possible. Will look into this soon! Thanks for so thoroughly testing things 🙌

**Comment by kaqu** [comment]
Ok, I will try to reproduce it outside or find if there is some other case here.

**Comment by kaqu** [comment]
This makes timeout:
```
func testWebView() {
        class VC: UIViewController {
            override func loadView() {
                let browser: WKWebView = .init()
                view = browser
                browser.load(URLRequest(url: URL(string: "url")!))
            }
        }
        let vc = VC()
        vc.view.frame = .init(x: 0, y: 0, width: 200, height: 200)
        assertSnapshot(matching: vc, as: .image)
    }
```
It turns out that it was loading url, but it was kind of invalid.

**Comment by kaqu** [comment]
I am wondering if loading other valid URL like base64 data which is accepted by browsers will behave similarly.

**Comment by stephencelis** [comment]
Ah. I think it’s kind of correct to fail in this case. Any way to modify your code to avoid the loading for the test? Or to load a valid HTML string instead?

**Comment by stephencelis** [comment]
(Up for other suggestions, too! We just want to wait for loading web pages to load.)

**Comment by stephencelis** [comment]
Going to close this issue and track the improvement here #136.
