### ISSUE TITLE
Question: Can the image comparision take into consideration some tolerance?

### ISSUE THREAD

**Issue by kandelvijaya** [pointfreeco/swift-snapshot-testing#127]
This is especially the case with FBSnapshot library which we use. We will like to switch to this one for recursive description text diff but might retain some image comparision. In  that case we might need some tolerance for check. Does the library support it at the moment. Sorry, didnt have time to dig into the code or try out yet.

**Comment by stephencelis** [comment]
Yup! Check out the docs for all available strategies and options here: https://github.com/pointfreeco/swift-snapshot-testing/blob/master/Documentation/Available-Snapshot-Strategies.md

**Comment by mbrandonw** [comment]
Hey @kandelvijaya, just wanted to make sure you saw Stephen's reply and found the snapshot strategy that takes into account [precision](https://github.com/pointfreeco/swift-snapshot-testing/blob/master/Documentation/Available-Snapshot-Strategies.md#uiview). If so, mind if I close this?

**Comment by kandelvijaya** [comment]
@mbrandonw @stephencelis thanks for answering. Will try to play with it when time permits. 

I will close this issue.
