### ISSUE TITLE
Unable to find a specification for `SnapshotTesting (~> 1.0)`

### ISSUE THREAD

**Issue by pawankmrai** [pointfreeco/swift-snapshot-testing#131]
Not able to install via cocoa pods.
https://cl.ly/a7de76ad96fd
```
Analyzing dependencies
[!] Unable to find a specification for `SnapshotTesting (~> 1.0)`

```
Podfile - configuration
https://cl.ly/3a1f6cfe9d21
```
 target "xyz" do
	  inherit! :search_paths
	  pod 'SnapshotTesting', '~> 1.0'
  end
```
Thanks

**Comment by yaakovgamliel** [comment]
Just for now i'm doing:
```pod 'SnapshotTesting', :git => 'https://github.com/pointfreeco/swift-snapshot-testing.git```

**Comment by mbrandonw** [comment]
Interesting, this currently works for me locally. Can you try `pod install --repo-update` to make sure you have the latest specs?

Thanks!

**Comment by pawankmrai** [comment]
> Just for now I'm doing:
> `pod 'SnapshotTesting', :git => 'https://github.com/pointfreeco/swift-snapshot-testing.git`

Working fine now.
One thing to note is **minimum iOS deployment version 10.0**, according to **SnapshotTesting.podspec**.

Thanks @yaakovgamliel
