### ISSUE TITLE
Thank you for the awesome library

### ISSUE THREAD

**Issue by broadwaylamb** [pointfreeco/swift-snapshot-testing#160]
I just wanted to say thank you for designing this thing. It's fascinating, really.

I'm currently working on a [PDF generation library](https://github.com/WeirdMath/SwiftyHaru) for Linux, which is a perfect use case for SnapshotTesting, and it's amazing how I can compare the generated PDF files and get a nice diff in both string format (which is convenient when I want to be sure that the PDFs have exactly the same internal structure) and image format (to see if a change in code resulted in a visible regression).

Keep up the good work.

**Comment by yaakovgamliel** [comment]
Love it to!!!, looking forward for contributing some code to

**Comment by mbrandonw** [comment]
@broadwaylamb thanks for sharing! your use of the library is something we hadn't even considered. To be able to snapshot values into a visual format like PDF but still diff the values as plain text is very cool!

**Comment by stephencelis** [comment]
Closing this to do some spring cleaning. Thanks again for sharing, though 😄
