### ISSUE TITLE
Weird reference size when running on travis

### ISSUE THREAD

**Issue by sarunw** [pointfreeco/swift-snapshot-testing#165]
My test run fine locally, but when I try to run it on Travis ci I got failed test with an error like this

`Expected snapshot@(320.0, 44.0) to match reference@(213.33333333333334, 29.333333333333332)`

I don't know why reference size showing weird resolution like 213.33333

Anyone experienced this before?

**Comment by mbrandonw** [comment]
This is most likely due to running tests on CI in a different simulator than what you run locally. You should try to keep them the same because there can be differences, like screen sizes and small rendering artifacts.

In this case of this `.333333`, that is most likely coming up because CI is running on a 3x device. You probably captured the snapshot locally on a 2x device, and so you will see:

```
320 = (3/2) * 213.33333333333334
44  = (3/2) * 29.333333333333332
```

The `3/2` factor is because you snapshot at 2x and are verifying on 3x.

Hope that helps!

**Comment by sarunw** [comment]
Yes, that is the case, but this error message is very misleading.
Shouldn't it be something like
> Expected snapshot@(960.0, 132.0) to match reference@(640, 88.0)

Instead of
> Expected snapshot@(320.0, 44.0) to match reference@(213.33333333333334, 29.333333333333332)

Don't understand what lib trying to do with that 3/2 factor if it want to make the test compatible with all device regardless of device running the test it should apply that factor against result of testing device 960x132 (3x device)

so it would be 960 x 2/3 = 640 which equal recorded reference size.

And I don't see any 1x 2x 3x information in reference image name, how can lib assume 2x in form factor?

**Comment by mbrandonw** [comment]
Yeah, that failure message isn't great and we can try to make it better.

> Don't understand what lib trying to do with that 3/2 factor if it wants to make the test compatible with all device regardless of a device running the test it should apply that factor against the result of testing device 960x132 (3x device)

When we say that you can take device agnostic screenshots, we mean that in one test suite you can take screenshots for various screen sizes, like small iPhone's and iPad's, and we'll override the trait environment to make it seem like it's really that device. This means you don't have to boot up multiple simulators just to capture those different sizes. However, if you run that test suite on different simulators you will get subtly different results. Bugs have been [filed](http://openradar.appspot.com/radar?id=4941361895702528) with Apple to try to bridge that gap, but they claim it works as expected.

**Comment by stephencelis** [comment]
This issue has gotten a bit stale so I'm going to close it out, @sarunw. If it's still an issue, or if you have suggestions to improve the error messaging, please let us know!
