### ISSUE TITLE
Tests passing in Xcode and failing on command line/CI

### ISSUE THREAD

**Issue by concertman** [pointfreeco/swift-snapshot-testing#174]
When I run the snapshot tests in Xcode everything passes just fine, but we noticed our CI was still failing. After running it locally in the command line we are noticing that whenever we run our tests from the command line we are getting a failure similar to the following:
```
SignUpViewControllerTests testSignUpViewControllerSnapshot] : failed - Expected snapshot@(320.0, 568.0) to match reference@(480.0, 852.0)
```

The test that is running is the following:
```swift
let vc = SignUpViewController()
assertSnapshot(matching: vc, as: .image(on: .iPhoneSe))
```

Have I misconfigured something? Any help would be greatly appreciated! Thank you!

**Comment by stephencelis** [comment]
Hey @concertman. Snapshots unfortunately render differently depending on the simulator. Even with trait collection overrides, it's impossible to make snapshots completely platform agnostic: you've gotta pick a simulator and make sure it's consistent across the team and CI.

From the error message, it looks like the screen shots were recorded using a 3x simulator (iPhone 8 Plus or iPhone XS Max), but CI is running tests using a 2x simulator.

**Comment by concertman** [comment]
@stephencelis Ah! Ok, I hadn't even thought about what sim the CI was running on. I've changed it and it's all working now. With that in mind how are you going about rendering the shots on a lower res device?

**Comment by stephencelis** [comment]
We'll try to update the README/documentation to make things more clear. We personally just use a 2x simulator and care more about how view layout is rendered over pixel scale fidelity.

Is there a reason you want to capture the 3x images? You could technically run tests in multiple simulators and capture multiple resolutions, but you'd need to encode the scale into the snapshot name.

``` swift
assertSnapshot(matching: vc, as: .image(on: .iPhoneSe), named: "@\(Int(UIScreen.main.scale))x")
```

You could write a local wrapper helper for this, too.

**Comment by concertman** [comment]
@stephencelis No particular reason. That's just the simulator I was running when I first ran the tests. If you recommend a 2X device then I'll use that. We'll look at the wrapper for it, but are just fine to do with out. We just weren't aware of that when setting it up. 

Thanks for the help and for sharing your framework!
