### ISSUE TITLE
dump of NSObject subclass includes address by default

### ISSUE THREAD

**Issue by pteasima** [pointfreeco/swift-snapshot-testing#186]
<img width="956" alt="Screenshot 2019-03-09 at 22 20 05" src="https://user-images.githubusercontent.com/1642679/54077548-3f02a900-42ba-11e9-9cde-75e9e8f16c82.png">

PR incoming when I find the time.

**Comment by stephencelis** [comment]
@pteasima We should be stripping out those memory addresses using this helper:  https://github.com/pointfreeco/swift-snapshot-testing/blob/4d426f65da1eb4b8f8c7fe2b108ad380ceded10f/Sources/SnapshotTesting/Snapshotting/Any.swift#L135-L137

If ya get a failing test case, though, please let us know what we're missing!

**Comment by stephencelis** [comment]
@pteasima Doing some spring cleaning here, so gonna close this one out. If you have a failing test case, though, we'd love to fix! 😄
