### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by finestructure** [pointfreeco/swift-snapshot-testing#190]
I've used snapshot testing in the past (I think around 1.0.0) with Linux but when I just added it to a new project I got the following:

```
Linking ./.build/x86_64-unknown-linux/debug/rester
/home/travis/build/finestructure/Rester/Tests/ResterTests/LaunchTests.swift:43:9: error: use of unresolved identifier 'assertSnapshot'
        assertSnapshot(matching: output, as: .description)
        ^~~~~~~~~~~~~~
```

I've added `SnapshotTesting` to the target (and `swift test` passes on macOS).

I see that you have linux tests set up in your `.travis.yml` file so I'm guessing this should be working?

Before I dig into this further is there perhaps something obvious I'm missing in my set up?

My `Package.resolved` contains

```
      {
        "package": "SnapshotTesting",
        "repositoryURL": "https://github.com/pointfreeco/swift-snapshot-testing.git",
        "state": {
          "branch": null,
          "revision": "1fb2e65cf62d2f983b3cab2871cbb218ea9ee9b7",
          "version": "1.3.0"
        }
      },
```

and my test target looks ok, I think:

```
        .testTarget(
            name: "ResterTests",
            dependencies: ["ResterCore", "SnapshotTesting"]),
```

**Comment by stephencelis** [comment]
Hi @finestructure! Are you subclassing `SnapshotTestCase`? Linux's current XCTest framework isn't quite as fleshed out as macOS's, so you need to use a subclass for `assertSnapshot` to work.

**Comment by finestructure** [comment]
Ah, that's it! Subclassing `SnapshotTestCase` does the trick. Thanks a lot for the quick response! :)
