### ISSUE TITLE
assertSnapshot(matching: vc, as: .image(on: .iPhoneXr)) on iPhone 8 simulator

### ISSUE THREAD

**Issue by ristkof** [pointfreeco/swift-snapshot-testing#192]
When snapshotting a view as this:

> assertSnapshot(matching: vc, as: .image(on: .iPhoneXr))

the view should be resized to match the resulting iPhoneXr's size. Without this the view controller's size typically depends on the size of the simulator on which the test is run.

So I think I would add

> view.setNeedsLayout()
> view.layoutIfNeeded()

somewhere in the prepareView function in View.swift, to make sure the view completes a layout cycle after having set the view.frame.size = size (line 486).

Or am I missing something else to achieve the same result?

**Comment by stephencelis** [comment]
@ristkof The view controller's view should definitely be getting resized with that call. As for some of these lifecycle methods, there's been some recent discussion as to various tweaks we may need to make here: 
https://github.com/pointfreeco/swift-snapshot-testing/issues/173

We have some tests for different trait sizes in the test suite here, though they're fairly simple. We've also battle-tested this lib on a relatively large iOS app and haven't had an issue with sizing.

Any chance you can push a branch with a failing test case for us to see?

**Comment by ristkof** [comment]
I think I am seeing indeed combinations of #173 and #180 in my testing and got confused. In any way, at the moment I can not reproduce anymore what I thought was happening, so I am closing this until I do find an issue that I can pin down that is different from those two mentioned issues.
