### ISSUE TITLE
Workaround Xcode bug

### ISSUE THREAD

**Issue by mbrandonw** [pointfreeco/swift-snapshot-testing#198]
Right now when you cmd+ctrl+option+U in a test file _while_ your cursor is outside the test case body, Xcode will run each test case twice in the same process. That causes problems with our automatic indexing of snapshot files.

**Comment by stephencelis** [comment]
I filed a radar. Not sure this is something we can really workaround in an effective way.

**Comment by stephencelis** [comment]
rdar://49203529
