### ISSUE TITLE
Specify View/ViewController Description Attributes

### ISSUE THREAD

**Issue by Sherlouk** [pointfreeco/swift-snapshot-testing#202]
One of the current supported strategies is recursiveDescription, this gets you lines like:

```
<UILabel; frame = (109.5 0; 50.5 30); text = 'Live'; gestureRecognizers = <NSArray>; layer = <_UILabelLayer>>
```

I understand this currently uses Apple's ObjC method under the same name, but was wondering if we created our own version if we would then be able to add the flexibility to specify exactly what attributes we want to be included in each of the views logs?

For instance I'd like to ensure that colour (text (where appropriate)/background colours) are all consistent. I also don't get much value from `layer = <_UILabelLayer>` in this test.

`.recursiveDescription(properties: [.colours, .text])` (intentionally simplified)

Needs a bit more fleshing and detailing, but does this sound within the scope of this project?

**Comment by stephencelis** [comment]
Hi @Sherlouk! We're definitely interested in what you come up with. SnapshotTesting's API should be completely open to define custom strategies from existing ones. You could ship this strategy as its own package, or if it makes sense, we could merge it into SnapshotTesting proper.

**Comment by Sherlouk** [comment]
Appreciate the comment, and have just read up on the documentation for creating custom strategies - I'll be sure to take a look at that for our project and see how it comes along!

I'll close this issue for now, and will open a PR (or a separate package) in the future if I can make something that would be valuable to the community!

Thanks Stephen!
