### ISSUE TITLE
Split Screen Image Size Presets

### ISSUE THREAD

**Issue by Sherlouk** [pointfreeco/swift-snapshot-testing#205]
I understand that it is possible to mimic split view layouts by using your own `ViewImageConfig` and passing in the relevant sizes and traits - but I wonder if this would be a handy addition to the library?

**Comment by stephencelis** [comment]
💯! That'd be a lovely addition!

**Comment by Sherlouk** [comment]
I've done some of the leg work and worked out all of the split screen (slide over uses the smallest split) sizes in both orientations on all the existing iPads.

@stephencelis What sort of API/naming do you think would be best for this?

```
     iPad Mini:
       Portrait:
         438x1024 (20, 0, 0, 0) H:Com V:Reg
         320x1024 (20, 0, 0, 0) H:Com V:Reg
    
       Landscape:
         694x768 (20, 0, 0, 0) H:Reg V:Reg
         507x768 (20, 0, 0, 0) H:Com V:Reg
         320x768 (20, 0, 0, 0) H:Com V:Reg

     iPad Pro (10.5-inch):
       Portrait:
         504x1112 (20, 0, 0, 0) H:Com V:Reg
         320x1112 (20, 0, 0, 0) H:Com V:Reg
    
       Landscape:
         782x834 (20, 0, 0, 0) H:Reg V:Reg
         551x834 (20, 0, 0, 0) H:Com V:Reg
         320x834 (20, 0, 0, 0) H:Com V:Reg
    
     iPad Pro (11-inch):
       Portrait:
         504x1194 (24, 0, 20, 0) H:Com V:Reg
         320x1194 (24, 0, 20, 0) H:Com V:Reg
    
       Landscape:
         809x834 (24, 0, 20, 0) H:Reg V:Reg
         592x834 (24, 0, 20, 0) H:Com V:Reg
         375x834 (24, 0, 20, 0) H:Com V:Reg
    
     iPad Pro (12.9-inch):
       Portrait:
         639x1366 (20, 0, 0, 0) H:Com V:Reg
         375x1366 (20, 0, 0, 0) H:Com V:Reg
    
       Landscape:
         981x1024 (20, 0, 0, 0) H:Reg V:Reg
         678x1024 (20, 0, 0, 0) H:Reg V:Reg
         375x1024 (20, 0, 0, 0) H:Com V:Reg
```

**Comment by Sherlouk** [comment]
I'm thinking because the options are different on portrait/landscape that we might want something like

```
.iPad(.portrait) // full
.iPad(.portrait(.oneThird))
.iPad(.portrait(.twoThirds))

.iPad(.landscape) // full
.iPad(.landscape(.oneThird))
.iPad(.landscape(.oneHalf))
.iPad(.landscape(.twoThirds))
```

The issue with this API is that you could in theory do `.iPhone(.portrait(.oneThird))` which would just do full size phone. (At time of writing 😉🤞) - This might be a bit confusing?

Would we then want a separate TabletOrientation which has the same two values but also the SplitView enum I mentioned above?

This would be a breaking change, unless we did some [struct magic](http://ilya.puchka.me/swift-enums-with-associated-values-defaults/) but that would reduce readability and add more confusion IMO. We could keep the existing init and just add an extra one if they wish to add this behaviour? Though we may need to change the signature slightly to prevent the compiler freaking out!

Couple different routes there, would love to know where you stand @stephencelis @mbrandonw 😄
