### ISSUE TITLE
[Question] QuickSpec with Randomized Execution Order

### ISSUE THREAD

**Issue by cheeseonhead** [pointfreeco/swift-snapshot-testing#206]
Right now the reference file naming seems to follow `methodName`.`executionOrder`. But in Quick everything is under `spec`, which will have files named `spec.1.txt`, `spec.2.txt`. When randomized execution order is turned on, these `it`s are also randomized, which means `1` might not be the same thing.

Are there workarounds to this?

**Comment by cheeseonhead** [comment]
Sorry it was my mistake, Quick doesn't seem to randomize it within one file.

**Comment by stephencelis** [comment]
:+1: The index is per test, so execution order hopefully shouldn't matter. You can always disable the index using the `named` parameter, though!

**Comment by cheeseonhead** [comment]
Yeah I get it when it's just `XCTest`, the naming make sense. But when using Quick the reference file is literally `spec.1.txt`. `spec` is not a placeholder, it came from the method you should override when doing Quick.

The file names don't take those string descriptions into account, is it even possible to use those as the file name?

For example:
```
class SnapshotTestSpec: QuickSpec {
    override func spec() {
        describe("sanity") {

            it("should work") {
                assertSnapshot(matching: "Hello World", as: .lines)
            }

            it("should not be effected by execution order") {
                assertSnapshot(matching: "John Cena", as: .lines)
            }
        }
    }
}
```
I will have two reference files: `spec.1.txt` and `spec.2.txt`. The former corresponds to `"should not be effected by execution order"` because it's lexicographically earlier, and latter will be `"should work"`.

Not asking this to be solved, just curious if this is known and intentional.

Thanks!

**Comment by stephencelis** [comment]
@cheeseonhead If you're also using Nimble, @Killectro has a nice plugin here: https://github.com/Killectro/swift-snapshot-testing-nimble
