### ISSUE TITLE
Swift 4.2 Compatiblity

### ISSUE THREAD

**Issue by marc-medley** [pointfreeco/swift-snapshot-testing#210]
While testing [`swift-html` v0.3.1](https://github.com/pointfreeco/swift-html/releases/tag/0.3.1) for compatibility on a Swift 4.2 development system, the fetch of dependency `swift-snapshot-testing` was found to not be Swift 4.2 compatible. 

Swift build process hangs at "Fetching https://github.com/pointfreeco/swift-snapshot-testing.git hangs."

swift-snapshot-testing Package.swift (as reference by swift-html v0.3.1) currently requires Swift 5.

``` bash
cd eval-vapor-leaf-stencil
swift package reset
swift build
# Fetching https://github.com/vapor/vapor.git
# Fetching https://github.com/vapor/leaf.git
# Fetching https://github.com/stencilproject/Stencil.git
# Fetching https://github.com/pointfreeco/swift-html.git  #   <--- fetches OK on 4.2 :-) 
# ...
# Fetching https://github.com/apple/swift-nio-ssl-support.git
# Fetching https://github.com/apple/swift-nio-ssl.git
# Fetching https://github.com/kylef/PathKit.git
# Fetching https://github.com/kylef/Spectre.git
# Fetching https://github.com/pointfreeco/swift-snapshot-testing.git  <--- hangs here!
```

**Comment by Sherlouk** [comment]
@stephencelis Are you still looking to tackle this shortly? Currently blocking us from upgrading 😞 

Happy to try and tackle it if you're busy?

**Comment by stephencelis** [comment]
@Sherlouk Would love any help on this! It's not blocking us so we haven't been motivated to address, but I'd be happy to help work with you to shepherd it home!

**Comment by stephencelis** [comment]
I believe this is fixed 😆
