### ISSUE TITLE
Snapshot for UI Testing

### ISSUE THREAD

**Issue by vaderdan** [pointfreeco/swift-snapshot-testing#216]
Is it possible to add strategy for XCUIElement. I need it because It will be cool to snapshot views during the uitests (running the whole app), instead of mocking parts of the app

I think that it have already `snapshot` method which provide snapshot object with `XCUIElementAttributeName` properties

Or use XCUIElement debugDescription

**Comment by stephencelis** [comment]
Hi @vaderdan! If `XCUIElement` provides a means of inspection, you _should_ be able to write a snapshot strategy against it: https://github.com/pointfreeco/swift-snapshot-testing/blob/master/Documentation/Defining-Custom-Snapshot-Strategies.md

If you (or anyone else) is interested in contributing a custom strategy back to the main repo, we'd happily take a PR!

**Comment by stephencelis** [comment]
Going to close this in favor of your PR: #224
