### ISSUE TITLE
Split View Incorrect Traits

### ISSUE THREAD

**Issue by Sherlouk** [pointfreeco/swift-snapshot-testing#218]
https://twitter.com/qdoug/status/1115397262950010880?s=20

According to this tweet iOS 12.2 has changed traits pertinent to Split View on the newest iPad. I haven't currently got access to the latest Xcode to validate this.

https://github.com/pointfreeco/swift-snapshot-testing/blob/master/Sources/SnapshotTesting/Common/View.swift#L301-L331

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stephencelis** [comment]
@Sherlouk Did you ever get around to exploring this? Should we keep this issue open or is it save to close out?

**Comment by Sherlouk** [comment]
Never got round to investigating - is likely still an issue (though relatively minor IMO)

**Comment by stephencelis** [comment]
Going to close this out for now. I'm in the process of triaging and categorizing open issues and while this would be a nice enhancement, it doesn't seem to be a blocker like others. Thank @Sherlouk!
