### ISSUE TITLE
Image comparison crashes with blank images

### ISSUE THREAD

**Issue by stephencelis** [pointfreeco/swift-snapshot-testing#226]
If an image is made up of blank pixels with alpha zero (which can happen easily for a UIView that might be hidden), the comparison function currently crashes (on `memcmp`, I believe).

**Comment by stephencelis** [comment]
Closing this as stale. I'm not sure it's still a problem, but if folks encounter it and can provide a repro we should be able to address it then!

**Comment by jambudi** [comment]
i am facing same issues right now. How to I can provide more details ?
