### ISSUE TITLE
Inline Snapshots: Escape Strings

### ISSUE THREAD

**Issue by stephencelis** [pointfreeco/swift-snapshot-testing#230]
A regular multiline literal currently records the following:

``` swift
_assertInlineSnapshot(matching: value, as: .json, with: """
[
  "[\"key\": \"value\"]"
]
""")
```

This will fail on repeat test runs because `\"` is interpreted by Swift as `"`. We should instead escape `\`s encountered:

``` swift
_assertInlineSnapshot(matching: value, as: .json, with: """
[
  "[\\"key\\": \\"value\\"]"
]
""")
```

_Or_ promote the literal to a raw literal:

``` swift
_assertInlineSnapshot(matching: value, as: .json, with: #"""
[
  "[\"key\": \"value\"]"
]
"""#)
```

There's probably _some_ paring trickiness around escaping raw literals, though we can cross those bridges later.

Related: #228

**Comment by mbrandonw** [comment]
👍 to the raw literal style, I think that solves it nicely!
