### ISSUE TITLE
URLRequest `curl` strategy header fields random order result in false negatives

### ISSUE THREAD

**Issue by edwinveger** [pointfreeco/swift-snapshot-testing#240]
I'm snapshotting URLRequests (using version 1.5.0), and I'm encountering an issue where the nondeterministic ordering of the request headers results in a false negative.

Consider the following test result:
```
@@ −1,9 +1,9 @@
 curl \
 	--request POST \
 	--header "Content-Type: application/json" \
−	--header "X-loggedin: true" \
+	--header "X-locale: en_US" \
 	--header "X-clientid: ISHP" \
 	--header "X-version: 1.0" \
−	--header "X-locale: en_US" \
+	--header "X-loggedin: true" \
 	--data '{\"myobject\":\"\"}' \
 	"https://my.url.com"
```

It is clear that the headers are equivalent, and the non-ordered nature of the SSL Dictionary is causing the test failure.

I have currently circumvented this by duplicating the `curl` static method, like so:

```
extension Snapshotting where Value == URLRequest, Format == String {
    
    /// A custom strategy which sorts the request headers.
    static let curlOrdered = SimplySnapshotting.lines.pullback { (request: URLRequest) in
        var components = ["curl"]
        
        // HTTP Method
        // ...

        // Headers
        if let headers = request.allHTTPHeaderFields {
            let ordered = headers.sorted {
                guard $0.key != $1.key else { return $0.value < $1.value }
                return $0.key < $1.key
            }
            
            for (field, value) in ordered where field != "Cookie" {
```

This fixes the issue.

Is this something that would be welcome in a PR?

**Comment by mbrandonw** [comment]
Hey thanks for the issue! And yeah, we'd definitely accept a PR to fix any inconsistencies in this snapshot strategy, but I'm not sure I fully understand yet.

It seems we are already sorting by the keys in `allHTTPHeaderFields`, so I don't see how the non-determinism is coming up. Can you explain a bit?

**Comment by edwinveger** [comment]
Thanks for the pointer - my dependency code was not up to date and the `.sorted()` call was not showing up in my `URLRequest.swift`(I see this was addressed in #214, so I will close this issue). 

Not sure why, though. Because the current Podspec on master is version 1.5.0, I assumed I had the latest code. I will investigate tomorrow why CocoaPods does not fetch the latest code.

FYI
Installed via CocoaPods:
Podfile:`pod 'SnapshotTesting'`
Podfile.lock: `SnapshotTesting (1.5.0)` 
Podfile.lock checksum: `SnapshotTesting: 9ca1d80f6322509a035856170c11d0571b1f7171`).

**Comment by mbrandonw** [comment]
Huh very strange, that commit 9ca1d80f6322509a035856170c11d0571b1f7171 doesn't even appear in our repo :/

Let us know what you find. Maybe we need to cut a new release to give cocoapods a kick in the butt.

**Comment by edwinveger** [comment]
I adjusted my Podfile to
`pod 'SnapshotTesting', :git => 'https://github.com/pointfreeco/swift-snapshot-testing.git', :branch => 'master'`
This correctly pulls in the latest (including `.sorted()`).
Changing it back to `pod 'SnapshotTesting'` and running `pod install` / `pod update` gives me the old file/version again. 
I suspect the CocoaPods master repo is not up to date, or perhaps needs a 1.5.1 release.
