### ISSUE TITLE
installing Swift Package through Xcode

### ISSUE THREAD

**Issue by natemann** [pointfreeco/swift-snapshot-testing#244]
When installing SnapshotTesting Package through Xcode, it looks like it is installing the previous .package file

```swift
let package = Package(
  name: "SnapshotTesting",
  products: [
    .library(
      name: "SnapshotTesting",
      targets: ["SnapshotTesting"]),
  ],
  targets: [
    .target(
      name: "SnapshotTesting",
      dependencies: []),
    .testTarget(
      name: "SnapshotTestingTests",
      dependencies: ["SnapshotTesting"]),
  ]
)

if ProcessInfo.processInfo.environment.keys.contains("PF_DEVELOP") {
  package.dependencies.append(
    contentsOf: [
      .package(url: "https://github.com/yonaskolb/XcodeGen.git", from: "2.3.0"),
    ]
  )
}
```
This causes errors to occur due to not having the minimum iOS 10 requirement

**Comment by stephencelis** [comment]
Sorry about that! We've been meaning to release 1.6.0 for awhile. I've queued one change up and will do that soon!

https://github.com/pointfreeco/swift-snapshot-testing/pull/245

You can use `master` if you need to unblock yourself in the meantime.

**Comment by stephencelis** [comment]
@natemann This good to close now?
