### ISSUE TITLE
[EarlGrey] rootViewController is dying after assertion

### ISSUE THREAD

**Issue by alteral** [pointfreeco/swift-snapshot-testing#247]
Hi,
I have an issue where [UIViewcontroller Snapshot Strategies](https://github.com/pointfreeco/swift-snapshot-testing/blob/master/Documentation/Available-Snapshot-Strategies.md#uiviewcontroller) is not working with rootViewController.

**Environment:**
- github "pointfreeco/swift-snapshot-testing" "1.5.0"
- github "google/EarlGrey" "1.15.1"

**Steps to reproduce:**

1. Create more than one tests (e.g.: 2)
2. First of them should contains assertSnapshot with [UIViewcontroller Snapshot Strategy](https://github.com/pointfreeco/swift-snapshot-testing/blob/master/Documentation/Available-Snapshot-Strategies.md#uiviewcontroller) and match rootViewController:
`assertSnapshot(matching: UIApplication.shared.keyWindow!.rootViewController! , as: .image)`
3. Run all tests

**Actual result:**
- there is a black screen after the first test with assertSnapshot()
- next tests will be failed

**Comment by edwinveger** [comment]
I use SnapshotTesting extensively in my projects. I never use an existing view controller (e.g., the key window's root view controller) but always create a new view controller for each test case. That gives me full control over the snapshot and the expected outcome.

**Comment by stephencelis** [comment]
@alteral This should be fixed by #316! I'm going to close this out, but please reopen if you're still encountering this issue.
