### ISSUE TITLE
Cannot find `libCwlPreconditionTesting.dylib` when installing 1.6.0 with SPM

### ISSUE THREAD

**Issue by adamcarter93** [pointfreeco/swift-snapshot-testing#263]
When linking SnapshotTesting to my Xcode project using Swift Package Manager, the build fails with the following:

```
clang: error: no such file or directory: '/Users/user/Library/Developer/Xcode/DerivedData/project-folder/Build/Products/Debug-iphonesimulator/libCwlPreconditionTesting.dylib'
Command Ld failed with a nonzero exit code
```

This doesn't happen with version 1.5.0 which builds as expected (however I cannot use that version due to the build failing for the minimum deployment target). Therefore I need to link against 1.6.0.

**Comment by adamcarter93** [comment]
Turns out this error is related to a different framework (Nimble)

**Comment by stephencelis** [comment]
Glad you were able to sort things out! The error's definitely puzzling, and doesn't even seem to mention Nimble!
