### ISSUE TITLE
SceneKit and SpriteKit have become unreliable in Xcode 11

### ISSUE THREAD

**Issue by stephencelis** [pointfreeco/swift-snapshot-testing#276]
#275 had to disable these CI tests because SpriteKit and SceneKit scenes no longer reliably render in Xcode 11. Sometimes they render just fine. Sometimes they don't render at all (transparent). Sometimes they render glitchy artifacts.

**Comment by ncreated** [comment]
Anyone with some inputs on this? I'm playing around with `SKScene`, `SKView` but no clue - seems random.

**Comment by stephencelis** [comment]
Going to close this since it's out of our control. Feedback should be filed with Apple 😖
