### ISSUE TITLE
Inline Snapshots: Multiline String Assertion

### ISSUE THREAD

**Issue by Sherlouk** [pointfreeco/swift-snapshot-testing#281]
I was shown a [nice blog](https://vojtastavik.com/2019/11/28/custom-multiline-assertion/) on the idea of multiline string assertions which shows exactly what part of a multiline string has changed.

I think this would work great with our "inline snapshots" to make it easier to know exactly what has failed!

![image](https://user-images.githubusercontent.com/15193942/70847114-4e6dde80-1e58-11ea-9a69-4cf11b92d1c2.png)

**Comment by stephencelis** [comment]
This would be very cool! Going to mark with enhancement and close. It's something we should consider when establishing goals for turning `_assertInlineSnapshot` into `assertInlineSnapshot` :smile:
