### ISSUE TITLE
Inline Snapshots: Invalid Assumption of Line Number

### ISSUE THREAD

**Issue by Sherlouk** [pointfreeco/swift-snapshot-testing#286]
If our function call is done across multiple lines, then inline snapshots can't find the speech marks it needs to record (and then deletes the contents of the file: #285)

Example:
```
_assertInlineSnapshot(
  matching: ...,
  as: .lines,
  with: ""
)
```

This is especially prominent in our tests as our "matching" is actually a block - which is over multiple lines. Our workaround has been to pull the block our as a var, and use that so the callsite is all on one line - but this isn't as nice.

**Comment by stephencelis** [comment]
Oh wow, that bug is bad! Thanks for reporting it! I'll try to look into it soon.

**Comment by stephencelis** [comment]
Since `_assertInlineSnapshot` is still "private," I'm going to close this for now. We'd like to have a single issue in the future to document the milestone in making it public, though, and we'll keep this in mind!
