### ISSUE TITLE
Swift 5.2 support (Xcode 11.4)

### ISSUE THREAD

**Issue by rjchatfield** [pointfreeco/swift-snapshot-testing#294]
Can not be compiled with Swift 5.2 in Xcode 11.4 beta 1.

It seems there is a "circular reference" with:

```swift
public static let recursiveDescription = Snapshotting<UIView, String>.recursiveDescription()
```

As a proposed fix, we could make it a computed property:

```swift
public static var recursiveDescription: Snapshotting { Snapshotting<UIView, String>.recursiveDescription() }
```

**Comment by stephencelis** [comment]
We merged a fix to `master` recently! Will try to cut a new version well before Swift 5.2 leaves beta.

**Comment by stephencelis** [comment]
(See #293) :)
