### ISSUE TITLE
Snapshot ignore traitCollection in UITableViewCell

### ISSUE THREAD

**Issue by dstranz** [pointfreeco/swift-snapshot-testing#302]
I figure out that starting from Xcode 11.3* traitCollection is not properly propagated to UITableViewCells during snapshot making.

I've added a test that visualize the problem in #301 

✅ Xcode 11.1
❌ Xcode 11.3
❌ Xcode 11.3.1
❌ Xcode 11.4 beta

**Comment by stephencelis** [comment]
Closing this since it appears to be fixed! Thanks @dstranz!
