### ISSUE TITLE
viewDidAppear did not called on iOS 13

### ISSUE THREAD

**Issue by sidepelican** [pointfreeco/swift-snapshot-testing#307]
on iOS 13, `UIViewController.viewDidAppear` not called. This is because the viewController is not cleaned correctly.

**Comment by mkko** [comment]
This issue with missing `viewDidAppear` breaks up some tests where view controllers are animated. Any plans getting this merged, @stephencelis, @mbrandonw, someone else?

**Comment by stephencelis** [comment]
Just merged #308 in!
