### ISSUE TITLE
Snapshotting view hierarchy throws error `UIViewControllerHierarchyInconsistency`

### ISSUE THREAD

**Issue by GHMarcus** [pointfreeco/swift-snapshot-testing#310]
We get an error after the update from `1.7.0` -> `1.7.2`
You can reproduce the issue with the attached project.
[SnapshottingHierarchyError.zip](https://github.com/pointfreeco/swift-snapshot-testing/files/4311661/SnapshottingHierarchyError.zip)

**Test Setup:**
We wanted to snapshot the view hierarchy with an `UITabBarController` as the `rootViewController` from the `window`.

**The complete error:**
```caught "UIViewControllerHierarchyInconsistency", "adding a root view controller <SnapshottingHierarchyError.TabBarController: 0x7fd277837200> as a child of view controller:<UIViewController: 0x7fd276d26a40>"```

**The issue?:**
I searched for the reason and found it in the `View.swift` file in the line `746`:

`rootViewController.addChild(viewController)`

In our case the given `viewController` is an `rootViewController` so it can't bet add as a child to another. By deleting this line everything works fine. 
Does this work as intended, or is it in this case a bug?
I will try to fix this issue and submit a PR in the next days. Maybe you can give me a hint. 

And finally...
Thanks for your great work, really like to work with this framework.

**Comment by stephencelis** [comment]
This should be fixed by #316. Please reopen if the issue persists, though!

**Comment by adamcarter93** [comment]
I'm still seeing this issue myself. Is there any update on it?

My current workaround is to take my child VC and call `removeFromParent()` before asserting snapshots.
