### ISSUE TITLE
Making snapshot with a present software keyboard?

### ISSUE THREAD

**Issue by MaxDesiatov** [pointfreeco/swift-snapshot-testing#312]
I understand that this library doesn't snapshot the whole simulator window, so probably it would be hard to include the software keyboard on a snapshot, but I'm wondering if it would still be possible somehow, even with some effort?

The use case is that we have a view contained in a scroll view, where a text input field should scroll up to stay visible when a software keyboard is present. Currently, I'm not sure if this is possible to test with `SnapshotTesting`, could anyone give any pointers or ideas on what's the best way to implement this?

**Comment by ixrevo** [comment]
Hi @MaxDesiatov, I think you could take a look at this episode https://www.pointfree.co/episodes/ep86-swiftui-snapshot-testing#t657 I'm not sure, but with UIWindow it might be possible to get a keyboard on a snapshot.

**Comment by stephencelis** [comment]
@MaxDesiatov This is definitely a neat idea and we'd definitely take a PR that implements it! We're doing some spring cleaning on the issues board, though, and want to keep it focused on bugs over feature requests, so I'm going to close this for now and tag it with "enhancement."
