### ISSUE TITLE
Can't find module if you uncheck any box that adds the SnapshotTesting package to any target

### ISSUE THREAD

**Issue by yzyczx** [pointfreeco/swift-snapshot-testing#323]
Can't find module if you uncheck any box that adds the SnapshotTesting package to any target in Step4.

**Comment by gobetti** [comment]
yeah the documentation could be more thorough but all you should need after following the xcode 11 steps from readme, is to manually add SnapshotTesting as a dependency to your tests target in the Build Phases (remember to include it in Link Binary With Libraries too)

**Comment by stephencelis** [comment]
@yzyczx Given @gobetti's solution do you consider this issue closed?

@gobetti Anything we can do to make the installation instructions clearer?

**Comment by gobetti** [comment]
hey @stephencelis yeah at least on my attempt, unchecking the box made the framework not be included anywhere so one has to manually add it to the tests target. This isn't mentioned in the readme. It may be obvious but my past experiences with SPM was through a Package.swift file and not through Xcode so I missed that instruction for 1 minute 😅

**Comment by stephencelis** [comment]
The README currently has the following instructions:

>> ⚠️ Warning: By default, Xcode will try to add the SnapshotTesting package to your project's targets. Please _uncheck_ SnapshotTesting in the final step of adding a Swift package to your target, as documented below.
>
> 1. From the **File** menu, navigate through **Swift Packages** and select **Add Package Dependency…**.
> 2. Enter package respository URL: `https://github.com/pointfreeco/swift-snapshot-testing.git`
> 3. Confirm the version and let Xcode resolve the package
> 4. On the final dialog, _uncheck_ any box that adds the SnapshotTesting package to any target

What do you think about the following update:
---
> ⚠️ Warning: By default, Xcode will add the SnapshotTesting package to your project's application and framework targets. Please _uncheck_ SnapshotTesting from application and framework targets in the final step of adding a Swift package to your project, as documented below.

 1. From the **File** menu, navigate through **Swift Packages** and select **Add Package Dependency…**.
 2. Enter package respository URL: `https://github.com/pointfreeco/swift-snapshot-testing.git`
 3. Confirm the version and let Xcode resolve the package
 4. On the final dialog, _uncheck_ any box that adds the SnapshotTesting package to application and framework targets (leave the box checked for any test target that need it)

**Comment by stephencelis** [comment]
Actually, even better: https://github.com/pointfreeco/swift-snapshot-testing/pull/327

Either Xcode SPM integration has gotten a lil better since we first wrote this up or I totally missed the "Add to Target" column earlier.
