### ISSUE TITLE
There is no iPad 9.7" size

### ISSUE THREAD

**Issue by zlib** [pointfreeco/swift-snapshot-testing#333]
SnapshotTesting.ViewImageConfig doesn't have such size.

**Comment by stephencelis** [comment]
Hi @zlib! Mentioned in #332 but we'd love a contribution if you have time to add it here: https://github.com/pointfreeco/swift-snapshot-testing/blob/dcaeca0b80d2efdd881c67cdd62f7478fc5bec9f/Sources/SnapshotTesting/Common/View.swift#L15

**Comment by stephencelis** [comment]
Fixed in #405.
