### ISSUE TITLE
CSS and images not loaded in WKWebView snapshot

### ISSUE THREAD

**Issue by finestructure** [pointfreeco/swift-snapshot-testing#345]
This is very likely not an issue with the Snapshot library itself but I'm hoping that perhaps you've got an idea what might be going wrong :)

I've been trying to snapshot webpages rendered with an HTML DSL but despite passing in the `baseURL:` parameter to `loadHTMLString` the pages always load without any CSS or images.

Here's the extension I'm using:

```
extension Snapshotting where Value == HTML, Format == NSImage {
    public static func image(precision: Float = 1, size: CGSize? = nil, baseURL: URL? = nil) -> Snapshotting {
        Snapshotting<NSView, NSImage>.image(precision: precision, size: size).pullback { node in
            let html = node.render()
            let webView = WKWebView()
            webView.loadHTMLString(html, baseURL: baseURL)
            return webView
        }
    }
}
```

I've also tried the `webView.takeSnapshot` variant metioned from the docs but with that the page snapshot is entirely blank.

Now I've recently had the same issue of missing resources in a Mac app and the reason there was that the app needed a network client entitlement to be able to load the resources:

```
	<key>com.apple.security.network.client</key>
	<true/>
```

However, my current project is a backend SPM project and there's no way to specify entitlements that I can see.

I've tried running with `swift test --disable-sandbox` without success.

Any pointers greatly appreciated! :)

**Comment by stephencelis** [comment]
Hey @finestructure!

Am I correct in this issue manifesting in the snapshots here? https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/tree/68230e154a572048b17809819b0bb0346aa2c380/Tests/AppTests/__Snapshots__/WebpageSnapshotTests

When I open the text-based snapshots, I see the following CSS:

```html
<link rel="stylesheet" href="/stylesheets/main.min.css?0"/>
```

I think what you need to do is somehow control the base URL when running tests to point them to the appropriate file path/directory that contains `main.min.css`.

**Comment by finestructure** [comment]
Hey @stephencelis - that's exactly right :)

I was hoping that the `baseURL` parameter would fix that?

https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/68230e154a572048b17809819b0bb0346aa2c380/Tests/AppTests/WebpageSnapshotTests.swift#L27

I think I might have a fighting chance to control url though, because we're using an html DSL. I'll give that a go, thanks for the pointer!

**Comment by stephencelis** [comment]
> I was hoping that the `baseURL` parameter would fix that?

Interesting! I hadn't really noticed this parameter before. Checking the docs it says:

> A file that is used to resolve relative URLs within the document.

So I wonder if it does not work with absolute URLs? Please let us know what you find!

**Comment by finestructure** [comment]
Mmm, unfortunately none of the following variants I've tried had any effect:

- `href="file:///Users/sas/Projects/SPI-Server/Public/stylesheets/main.min.css?0"`
- `href="/stylesheets/main.min.css?0"`
- `href="stylesheets/main.min.css?0"`

neither with nor without a `baseURL` of `file:///Users/sas/Projects/SPI-Server/Public/`.

What did work was

- `href="https://swiftpackageindex.com/stylesheets/main.min.css?0"`

i.e. pulling in the live css. But that's no good for a snapshot test...

I guess I _could_ try and spin up a server on localhost and inject `http://localhost:8080` as the `baseURL` but that seems awfully convoluted.

I'm pretty sure this is a permission issue just like what I saw in my Mac app.

Anyway, thanks for taking a look!

Please feel free to close this issue unless you want to keep it around for reference/further input!

**Comment by stephencelis** [comment]
Going to close this now as we triage things. We think discussion around best practices for such a thing could be helpful in the future, though! Thanks again, Sven!

**Comment by finestructure** [comment]
For anyone coming across this via search, we've hacked our way around it by copying everything into a temp directory: 

- https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/main/Tests/AppTests/Helpers/TempWebRoot.swift
- https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/36b8434b6050d9b31913ef3c2347414de70ff197/Tests/AppTests/Util%2BSnapshotting.swift#L43
