### ISSUE TITLE
Compiler error when snapshotting a SwiftUI View

### ISSUE THREAD

**Issue by jpsim** [pointfreeco/swift-snapshot-testing#347]
Using the following test code:

```swift
import SnapshotTesting
import SwiftUI
import XCTest

class SnapshotTests: XCTestCase {
    func testEmptyView() {
        assertSnapshot(matching: EmptyView(), as: .image())
    }
}
```

I get the following compiler error:

```
Cannot convert value of type 'EmptyView' to expected argument type 'CALayer'
```

To reproduce, clone the Milestones repo with the `snapshot-tests` branch checked out and attempt to run tests for the MilestonesCore scheme. https://github.com/jpsim/Milestones/compare/snapshot-tests

<img width="983" alt="image" src="https://user-images.githubusercontent.com/474794/83949791-8ee06080-a7da-11ea-932c-e59a355b5177.png">

I'm using Xcode 11.5 (11E608c).

**Comment by jpsim** [comment]
If I embed the SwiftUI View in a `UIHostingController` it works:

```swift
let vc = UIHostingController(rootView: EmptyView())
assertSnapshot(matching: vc, as: .image())
```

**Comment by mbrandonw** [comment]
Hey @jpsim, we only just recently merged [support](https://github.com/pointfreeco/swift-snapshot-testing/blob/4d9e7447dc5ce3b1ad3757cbf2d4387bf8e35934/Sources/SnapshotTesting/Snapshotting/SwiftUIView.swift) for SwiftUI views and looks like we haven't yet cut a release. You could target that SHA for now, and we'll cut a release soon!

But yeah, a totally fine work around is to put the view in a hosting controller.

**Comment by jpsim** [comment]
Ah, sorry I saw the SwiftUI tests in this repo and incorrectly assumed that support was already included in the latest release.
