### ISSUE TITLE
Xcode 12 Beta name clash

### ISSUE THREAD

**Issue by xavierLowmiller** [pointfreeco/swift-snapshot-testing#360]
In Xcode 12, there's a new method on `XCTestCase`: [`record(_ issue: XCTIssue)`][1].

Unfortunately, this clashes with SnaphotTesting's `record` boolean:

```swift
record = true
^^^^^^ Cannot assign to value: 'record' is a method
```

This can be worked around by prefixing the module name:

```swift
SnapshotTesting.record = true // Works fine
```

Still, I believe that it's unlikely that Apple will rename the new method until the release Xcode 12, so I suggest renaming the boolean `record`.

If you're interested, I'd love to submit a pull request.

[1]: https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes

**Comment by stephencelis** [comment]
I think we can move towards `isRecording`, with `record` deprecated in the meantime, if you'd like to take a pass at that.

**Comment by xavierLowmiller** [comment]
Thanks! I'll give it a try.
