### ISSUE TITLE
Tests failing after adding a new asset.

### ISSUE THREAD

**Issue by emilianoHualpa** [pointfreeco/swift-snapshot-testing#369]
Hi, thanks for developing this framework, it's very helpful.

We have been experiencing some issues in our project, after adding a new asset, unrelated tests are failing showing a diff of an image that was not updated.

To clarify: I add a new asset (called B.pdf for BViewController) and random tests fails (diff in A.pdf in AViewController)
![image](https://user-images.githubusercontent.com/1564689/86574843-bc096580-bf76-11ea-8525-fe38fa932676.png)
This pencil was not changed/updated at all, and it's failing now after adding a new asset for another ViewController (unrelated to this one).

Thanks

**Comment by mbrandonw** [comment]
This seems like an iOS bug 😕

One explanation for this could be if Xcode combines all of the assets in the catalogue into one big texture map. If that is the case then adding/editing any asset may very slightly modify the entire texture as it tries to compile it down into the most efficient space.

So unfortunately I don't think there is much we can do here. It's possible that the new SVG capabilities might help with this if they aren't rasterized upon compilation, but I'm not sure if that is the case either.

**Comment by emilianoHualpa** [comment]
thanks for the quick response! We'll continue investigating in our own, as soon as we find a clue or solution we'll try to keep everyone on the loop.

**Comment by emilianoHualpa** [comment]
We've find out that when you are not using the latest version (on your machine) of the simulator, the tests fail.
For example:
You have the latest iPhone 11.6 simulator, but you run the tests on the iPhone 11.3 sim, they fail.
But if in another machine, the latest sim is 11.3, they pass.

**Comment by domagojstankovic** [comment]
Also happening here. Tests are failing even on the latest simulator.
