### ISSUE TITLE
Strategy for storing snapshots

### ISSUE THREAD

**Issue by buscarini** [pointfreeco/swift-snapshot-testing#380]
I'm wondering what would be a good strategy for storing snapshots. I started using this and I ended with a repository that was more than 2 GB, which is the maximum supported by BitBucket, so I had to create a different repo and disable all snapshot testing. ¿Do you store this only in a CI machine? ¿Can you specify a different root folder so you can have snapshots saved outside of the current repository?

**Comment by stephencelis** [comment]
@buscarini Have you looked into git-lfs? https://git-lfs.github.com

**Comment by Sherlouk** [comment]
We're actually going through a very similar conversation internally at the moment - we've got solutions varying from LFS (as Stephen mentioned above) and Git Submodules down to S3/cloud storage and internal CI caches.

@stephencelis Do you have any more details on how exactly you'd setup LFS for this?

**Comment by stephencelis** [comment]
@Sherlouk I think you could probably do something like `git lfs track "*/__Snapshots__/*.png"`. We've been meaning to adopt it on some of our own repos but haven't gotten around to it yet.
