### ISSUE TITLE
Override loadView leads to view with zero size

### ISSUE THREAD

**Issue by MasterWatcher** [pointfreeco/swift-snapshot-testing#381]
Hello and thank you for such a great snapshot testing tool! 

I would like to have my layout in separate UIView and replace it in `loadview` like this:

```
class MyViewContoller: UIViewController {
    override func loadView() {
        view = MyView()
    }
}

class MyView: UIView {
    init() {
        super.init(frame: .zero)
        backgroundColor = .red
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

but when I'm trying to assert it:
```
class MyViewControllerTests: XCTestCase {

    func testMyViewController() {
        let vc = MyViewContoller()
        assertSnapshot(matching: vc, as: .image)
    }
}
```

I got the error
<img width="400" alt="test_threeHoursSelected 1" src="https://user-images.githubusercontent.com/739803/92493635-69aa2680-f1fd-11ea-8fc9-ec67ea517398.png">

How can I deal with that?

**Comment by stephencelis** [comment]
@MasterWatcher you need to specify a size for a view to be snapshottable. You can specify the size as an argument to `.image`: https://github.com/pointfreeco/swift-snapshot-testing/blob/main/Documentation/Available-Snapshot-Strategies.md#image-11

**Comment by MasterWatcher** [comment]
Works as expected, thanks!
