### ISSUE TITLE
Dark Mode Support 

### ISSUE THREAD

**Issue by MasterWatcher** [pointfreeco/swift-snapshot-testing#384]
I'm looking for an opportunity to test my ui components in dark mode. I found some pull requests (https://github.com/pointfreeco/swift-snapshot-testing/pull/337, https://github.com/pointfreeco/swift-snapshot-testing/pull/303, https://github.com/pointfreeco/swift-snapshot-testing/pull/252, https://github.com/pointfreeco/swift-snapshot-testing/pull/251) but none of these are merged.

**Comment by LConradLB** [comment]
Dark mode support is already supported by overriding the user interface style on the hosting controller

`
let vc = UIHostingController(rootView: ViewToTest())
vc.view.frame = UIScreen.main.bounds //Set frame
vc.overrideUserInterfaceStyle = .dark //Set dark mode trait
`

**Comment by clausjoergensen** [comment]
@LConradLB UIHostingController is only for SwiftUI. From what I can tell, nothing have happened in terms of dark mode support for SnapshotTesting in the past 13 months :(

**Comment by Sherlouk** [comment]
Dark mode is not specific to the Snapshot Testing library, rather it's a trait that your UI adapts to.

You can do this in one of two ways.

You can, as Lewis shared above, set `overrideUserInterfaceStyle` on any UIViewController. Their example is of the SwiftUI Hosting Controller but it can also be for any normal view controller.

You can also pass through an array of traits to the SnapshotTesting function. I'm not at a compiler right now, but it looks something like this:

```swift
assertSnapshot(matching: viewController, as: .image(traits: .init(userInterfaceStyle: .dark)))
```

And for those who are using SwiftUI directly, it is possible to set the environment variable. Which looks something close to this:

```swift
YourView()
    .environment(\.colorScheme, .dark)
```

It is not necessary for the SnapshotTesting package to do anything specific for dark mode as it completely depends on your UI. In fact, in one of my applications I have my own theming system which means I have to pass through the theme object when I instantiate my view. Everybody's app will be different, but the points above will hopefully help with yours.
