### ISSUE TITLE
Carthage compatibility / Xcode project

### ISSUE THREAD

**Issue by mdiep** [pointfreeco/swift-snapshot-testing#39]
Hi! 👋 

Would you accept a PR to add an `.xcodeproj`, making this library Carthage compatible?

**Comment by mbrandonw** [comment]
Hey! We would totally take a PR for that! In fact, while yer there could you throw this in the `Makefile` so that it's easy to regen the `xcodeproj` file?

```
xcodeproj:
	swift package generate-xcodeproj
	xed .
```
