### ISSUE TITLE
No such module 'SnapshotTesting'

### ISSUE THREAD

**Issue by yangwulong1978** [pointfreeco/swift-snapshot-testing#407]
I followed https://troz.net/post/2020/swiftui_snapshots/
to add SnapshotTesting  in project, get No such module'SnapshotTesting' error

my Xcode is 12.1, swift 5.3, latest mac

**Comment by duybui297** [comment]
Try to add `https://github.com/pointfreeco/swift-snapshot-testing` by adding a new Swift package dependency to your project
And remember to specific Test target - not your production target

**Comment by stephencelis** [comment]
Going to close this out for now, as it seems to be the missing package, suggested in the follow-up comment. If you still have issues in the future, please let us know!
