### ISSUE TITLE
Could I know the reason of this Warning?

### ISSUE THREAD

**Issue by guts0808** [pointfreeco/swift-snapshot-testing#408]
> Warning: Snapshots must be compared using a simulator with the same OS, device gamut, and scale as the simulator that originally took the reference to avoid discrepancies between images.

Could I know the reason of this Warning?
I would like to and am trying to remove above dependency from Snapshot testing. 
since it's very painful checking all so many snapshots one by one whenever update OS of simulator
and It also hard to check all supporting OS version.

**Comment by stephencelis** [comment]
There's discussion here: https://github.com/pointfreeco/swift-snapshot-testing/discussions/505
