### ISSUE TITLE
Disable filename counter

### ISSUE THREAD

**Issue by h0shy** [pointfreeco/swift-snapshot-testing#429]
Is there a way to disable the counter at the end of the filename? We use the iOS version in the end of the name and to have `.1` after each name is confusing. Any help would be much appreciated :)

**Comment by odisei369** [comment]
You could add `named:` parameter. Then library will not add this counter at the end of a file.

Example:
```swift
assertSnapshot(matching: view, as: .image, named: "my_view")
```

I hope it helped and we could close the issue.

**Comment by dafurman** [comment]
With the following example:
```
class MyViewControllerSnapshotTests: XCTest {
    func testLayout() {
        assertSnapshot(matching: MyViewController(), as: .image)
    }
}
```

Using "my_view" in a test would result in the following file name:
`MyViewControllerSnapshotTests/testLayout.my_view.png`
I think I'm in the same situation as @h0shy, where I'd really just be happy with a parameter or static var that disables the counter / suffixing, to have the full file path be: `MyViewControllerSnapshotTests/testLayout.my_view.png`.

I usually try to have one test correspond with one snapshot, so the simplest naming scheme for me would be to have the snapshot images match the test names, without adding any suffixes.

**Comment by stephencelis** [comment]
Hi @dafurman! Thanks for the PR. I'm going to close this issue in favor of tracking the problem there, where we can discuss things further.

**Comment by Deco354** [comment]
@stephencelis The fork containing this PR has been deleted. Can we reopen this issue?

**Comment by dafurman** [comment]
Yup, +1 to the issue being reopened. I mistakenly closed that PR while cleaning out some of my Github repo forks. I forgot about that PR. I recreated it here: https://github.com/pointfreeco/swift-snapshot-testing/pull/747
