### ISSUE TITLE
storyboard with custom view produce incorrect screen shots

### ISSUE THREAD

**Issue by dorsafamara50** [pointfreeco/swift-snapshot-testing#433]
I am using snapshottesting framework to take screen shot. the framework is great. However there is problem.
In my storyboard I have a view with a custom button. the button sets the font of the title (system font)
when I take the screen shot, the screen shot represents a button without a tile. when I delete the line that sets the font, the screen shot is ok.
Is there any way to fix that please?

`    func setupView() {
        titleLabel?.font = titleFont (this is the line I am talking about)
        tintColor = setTitleTintColor()
        }
    }`

**Comment by mstultz** [comment]
Are you saying `setupView()` is not being triggered?

**Comment by stephencelis** [comment]
Hi @dorsafamara50! Thanks for the report and sorry for not responding till now. We're closing out old issues without enough information to reproduce. If this is still an issue, can you re-open it with a sample project that reproduces the problem? If you do not believe it's a library bug, and instead have a question on library use, please open a discussion, instead.
