### ISSUE TITLE
Seeing lots of screenshot failures when screenshots match lately

### ISSUE THREAD

**Issue by zablaetna** [pointfreeco/swift-snapshot-testing#437]
This was an issue in the past with other frameworks but I am seeing it a lot more lately on this one. I'll get a screenshot failure when the screenshots seem to match. I'm imagining some pixel is off by the tiniest bit perhaps...because of how it's rendered run to run?

Is there a way to reduce the matching requirement by just a bit? How is this not a match?

(Screenshot is a Git Tower output after I deleted the old screenshot and created a new one. An easy way to show both side by side.)

<img width="755" alt="Screen Shot 2021-03-04 at 9 06 02 AM" src="https://user-images.githubusercontent.com/56562474/109993403-7cdc1180-7cc9-11eb-8a35-92ba159a355d.png">

**Comment by okaverin** [comment]
Screenshots made on iOS 14.3 don't match iOS 14.4, even though the difference is not possible to see. Could this be the case?
