### ISSUE TITLE
How to include UIAlertController in a snapshot?

### ISSUE THREAD

**Issue by haemi** [pointfreeco/swift-snapshot-testing#445]
I would like to test the showing of a alert/actionsheet, but obviously it's neither included in the view nor in the viewController, as the UIAlertController is connected to the UIWindow.

Is there a way to include it in a snapshot nevertheless?

**Comment by KacperCzapp** [comment]
Any news on this? It would be very useful to be able to capture it.

**Comment by stephencelis** [comment]
I'm going to convert this to a discussion. While we've been able to capture alerts in screen shots in the past, we've also noticed the ability break over iOS releases :( We're not sure if it's possible these days, but maybe others who've had luck can weigh in there.
