### ISSUE TITLE
Fails to build on Xcode 12.5 Beta 3

### ISSUE THREAD

**Issue by CraigSiemens** [pointfreeco/swift-snapshot-testing#447]
We building either be cloning the repo or with Carthage, the following errors are produced.

```
.../swift-snapshot-testing/Sources/SnapshotTesting/AssertInlineSnapshot.swift:43:3: Cannot find 'XCTFail' in scope
.../swift-snapshot-testing/Sources/SnapshotTesting/AssertInlineSnapshot.swift:152:22: Type 'XCTContext' has no member 'runActivity'
.../swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:52:3: Cannot find 'XCTFail' in scope
.../swift-snapshot-testing/Sources/SnapshotTesting/AssertSnapshot.swift:280:22: Type 'XCTContext' has no member 'runActivity'
```

Seems like it could be related to `libswiftXCTest` being replaced in the Xcode 12.5 releases. A similar issue occurred with https://github.com/Quick/Nimble/issues/855 where they updated to use `lXCTestSwiftSupport`.

I quickly tried adding a "Link Binary with Libraries" build phase with XCTest.framework and it successfully built. But I haven't been able to test whether it works correctly when imported into other tests.

**Comment by amadeu01** [comment]
I'm still facing the same problem with Xcode 13

**Comment by CraigSiemens** [comment]
You'll have better luck creating a new issue than replying on this one. The Merged PR fixed the issue for us.
