### ISSUE TITLE
When a specific asset has updated, all snapshots fail

### ISSUE THREAD

**Issue by chosa91** [pointfreeco/swift-snapshot-testing#449]
**Given**
Deployment target: iOS 13.0
SnapshotTesting: 1.8.2

**When**
We update one of our asset under the **Assets.xcassets** file
from [profileIcon.pdf](https://github.com/pointfreeco/swift-snapshot-testing/files/6237089/profileIcon.pdf) to [profileIcon2.pdf](https://github.com/pointfreeco/swift-snapshot-testing/files/6237093/profileIcon2.pdf)

Asset (non-default) preferences:
- Render As: Template Image
- Resizing: Preserve Vector Data
- Scales: Single Scale

**Then**
More than 400 snapshots fail, even those not affected by this change - in fact, this image is only on 1 screen so far, it should have 8 snapshots to touch. Although the test attachments don't show any difference, it's pure black. Sometimes on the corners show 1-1 pixel diff 😞

**Comment by chosa91** [comment]
Other cases had the same effect _(randomly failing snapshots)_:
- renamed an asset
- updated an asset
- removed an asset

So something around ***.xcassets** isn't right, but I'm not sure that this is related to the lib or not

**Comment by stephencelis** [comment]
This might be related to how Apple "compiles" assets into sprites. They may result in changes that are not really visible to the naked eye, but _are_ there. This isn't something we think we can really work around, short of directing you to use `precision` to not do a pixel-perfect assertion, unfortunately.

**Comment by chosa91** [comment]
@stephencelis Thanks for the suggestion, we will live with the precision reduction.

**Comment by ZevEisenberg** [comment]
I saw a similar issue just now. In this case, the difference between breaking and not breaking the snapshots was whether I set a new asset as single-scale (this was fine) or multi-scale with the image set as the 2x asset (this caused snapshot tests in unrelated views to start failing. This is an iPad-only app, so we're doing 2x-only graphics, which could have been a factor.
