### ISSUE TITLE
New release for Xcode 12.5

### ISSUE THREAD

**Issue by CraigSiemens** [pointfreeco/swift-snapshot-testing#460]
Now that the Xcode 12.5 RC is out and the fix for adding support for it is in main #455, it'd be nice to have a new release for it.

**Comment by CraigSiemens** [comment]
@stephencelis Would it be possible to make a new release for this now that Xcode 12.5 has been released?

**Comment by stephencelis** [comment]
@CraigSiemens Done! https://github.com/pointfreeco/swift-snapshot-testing/releases/tag/1.9.0

**Comment by CraigSiemens** [comment]
Thank you! 👍
