### ISSUE TITLE
Snapshots don't produce consistent results (.image)

### ISSUE THREAD

**Issue by tonyhunt** [pointfreeco/swift-snapshot-testing#461]
**Description**
I'm trying to implement `.image` snapshots for view controllers.

**Problem**
For more complex view controllers that make a few network requests and have several states (loading, loaded, error), I'm experiencing an issue where (even when using the `.wait()` function) the view controller is not fully loaded when the snapshot is taken.

When I test on multiple devices with something like this:
```
func verifyViewController(viewController: UIViewController, named name: String, status: ViewState, with entilement: UserState) {
    // Set size of snapshots
    let size: CGSize = .init(width: 390, height: 2000)
    let delay: TimeInterval = status == .loaded ? 5 : 0
    
    // Choose devices to test
    let devices: [String: ViewImageConfig] = ["iPhoneX": .iPhoneX, "iPhone8": .iPhone8, "iPhoneSe": .iPhoneSe]
    
    // isRecording = true
    
    // For each device, verify the snapshot
    let results = devices.map { device in
        verifySnapshot(matching: viewController,
                       as: .wait(for: delay, on: .image(on: device.value, size: size)),
                       named: "\(device.key)",
                       testName: "\(name)-\(status.rawValue)-\(entilement.rawValue)")
    }
    
    // Check that no errors were thrown
    results.forEach { XCTAssertNil($0) }
}
```

```
class ExampleUITests: XCTestCase {
    
    override class func setUp() {
        super.setUp()
    }
    
    override class func tearDown() {
        super.tearDown()
        HTTPStubs.removeAllStubs()
    }
    
    func testExampleViewController() {
        // Setup stubs
        stubResponse(path: "/example", filename: "file.json")
        stubResponse(path: "/anotherExample", filename: "file2.json")
        
        // Create view controller
        guard let exampleViewController = UIStoryboard(name: "Example", bundle: nil).instantiateInitialViewController() else {
            XCTFail("ExampleViewController not found")
            return
        }

        // Take the snapshot
        verifyViewController(viewController: exampleViewController, named: "ExampleViewController", status: .loaded, with: .premium)
    }
    
}
```

I get 3 snapshots in 3 completely different states (one loading, one almost loaded, one fully loaded). Ideally, all of these snapshots should be of the same view controller in the same state (fully loaded).

The snapshots do not always occur in the same order, but the first snapshot is always in a loading state, the second one is almost loaded (sometimes fully loaded), and the last one is always perfect / fully loaded.

Does anyone know why I'm getting different results? Or how I am supposed to make sure that the snapshots are consistent?

Example of this issue:

1. Loading
https://user-images.githubusercontent.com/23180788/115765833-1932a400-a35c-11eb-868c-2f010f79c3fc.png

2. Almost loaded / mid render (missing a few UI elements)
https://user-images.githubusercontent.com/23180788/115765826-1768e080-a35c-11eb-9ca7-9e7fa07ffd80.png

3. Loaded
https://user-images.githubusercontent.com/23180788/115765837-19cb3a80-a35c-11eb-9e1f-3dbb46bfc208.png

It's worth mentioning that running the test on a single device produces one snapshot in the loading state (the 1st picture above). So it seems like the more tests I run, the further along the view controller is in its initialization process, but the view controller should obviously be setup the first time it's tested. (extending the duration of the `.wait()` does not work)

I've tried to hack around this with triggering lifecycle events for the view controllers before passing it in to `verifySnapshot()` or `assertSnapshot()`, but nothing has worked, and I feel that this should be handled by the lib anyway. Any tips / advice would be much appreciated.

**Tools**
- OS: `Big Sur 11.2.3`
- `Xcode 12.4`
- `SnapshotTesting 1.8.2`
- ViewImageConfigs used: `.iPhoneX`, `.iPhone8`, ` .iPhoneSe`

**Comment by alekseevpg** [comment]
@tonyhunt hey, i'm experiencing the same issue. How did you solve this?
