### ISSUE TITLE
Landscape NavigationController gets (incorrect) top padding

### ISSUE THREAD

**Issue by chosa91** [pointfreeco/swift-snapshot-testing#463]
**Given**
Simulator: iPhone11@14.4 portrait
SnapshotTesting: 1.8.2

[test project](https://github.com/chosa91/SnapshotTestingPlayground)

**When**
```swift
let blank = UIViewController()
let sut = MyViewController()
let nav = UINavigationController(rootViewController: blank)
nav.setViewControllers([blank, sut], animated: false)
// nav.navigationBar.backgroundColor = .yellow
assertSnapshot(matching: nav, as: .image(on: .iPhone11(.landscape))
```

**Then**

SnapshotTesting/Common/View.swift:805
```
(lldb) po viewController.view.safeAreaInsets
▿ UIEdgeInsets
  - top : 48.0
  - left : 44.0
  - bottom : 24.0
  - right : 44.0
```

<img width="896" alt="testWithAppearanceMenu 2" src="https://user-images.githubusercontent.com/8747662/116076521-a21b4980-a694-11eb-8db5-353a076d08c9.png" >

Do you have any advice?

**Comment by chosa91** [comment]
Tried the following (none of the them worked):
- override orientation on a custom `NavigationController` instance
- use `UINavigationControllerDelegate`

**Comment by NikoSahradyan** [comment]
Hey @chosa91. I'm currently facing this issue and the problem is that in same `XCTestCase` I have multiple tests and **only for one** of them navigation controller is behaving this wrong.
How did you manage to resolve this issue?

**Comment by chosa91** [comment]
@NikoSahradyan We've accepted the problem and just commented next to the assertion _so that those who later get it wrong will be aware of it_. Then all of a sudden we saw that the snapshots were fixed, so it _"fixed itself", although I know that's not much help_ 😞
