### ISSUE TITLE
recording not working on macOS BigSur for Mac apps

### ISSUE THREAD

**Issue by toddwbates** [pointfreeco/swift-snapshot-testing#473]
I get this error 
"failed - You don’t have permission to save the file “testCardPreview2.1.png” in the folder “SmoothTransitionsTests”.func"
after running this code for a MacOS application.

testCardPreview2() throws {
		// exicutes action
		CardView_Previews.no_op(.tapped)
		isRecording = true
		assertSnapshot(matching: CardView_Previews.previews.toVC(width: 100, height: 200), as: .image)
	}
 
If I add any image with the right name I can record over it. However after a known good exists the "Newly-taken snapshot" is always successfully written to the tmp directory. If the "Newly-taken snapshot" were written to disk before testing a user could then copy files from the tmp directory to the known good directory. Generally I just copy the whole tmp directory and
 then use git to check the new files.

**Comment by tillhainbach** [comment]
This is due to the fact that unittest suites are run from inside a host application which are sandboxed by default (and thus they don’t have permission to write to the users filesystem). You can set „Host Application“ to „none“ and your views should get snapshotted as expected.

**Comment by stephencelis** [comment]
I'm going to close this out because @tillhainbach has provided a fix, but @toddwbates if you still believe this is an issue with the library, let us know. If you have a question about library use, instead, please open a discussion instead.
