### ISSUE TITLE
snapshots on ios15 have less top-pading than ios14

### ISSUE THREAD

**Issue by sisoje** [pointfreeco/swift-snapshot-testing#479]
Snapshot testing does not work the same on ios15 and ios14

I tried xcode13 with ios14 simulator and it works ok, but with ios15 simulator tests fail because there is less top-padding on snapshots. ignoreSafeAre() does not make a difference

ios15:
<img width="256" alt="testAccountCellView_ios15" src="https://user-images.githubusercontent.com/3493524/122538824-39fb3b00-d027-11eb-9f7d-e1b78a5dacec.png">

ios14:
<img width="256" alt="testAccountCellView_ios14" src="https://user-images.githubusercontent.com/3493524/122538827-3b2c6800-d027-11eb-9a7f-f3ffb838f244.png">

**Comment by Nikoloutsos** [comment]
Hi there according to the documentation depending on iOS version you may have different results.
This means that you need to maintain same device model and iOS version.

**Comment by sisoje** [comment]
ok then we will maintain it

**Comment by sisoje** [comment]
i did it today, instead of naming directory just "__Snapshots__" I add also device-name and OS version to the directory-name

the lib has poor support to do that out of the box as i see...

**Comment by stephencelis** [comment]
Going to close this, but we'll hopefully offer better default support for taking OS/simulator into account in the future.
