### ISSUE TITLE
failed - Snapshot does not match reference.

### ISSUE THREAD

**Issue by Shahzaib31** [pointfreeco/swift-snapshot-testing#492]
Snapshots pass on local machine but fails on CI. The device is same on local machine and CI.
`platform=iOS Simulator,name=iPhone 12,OS=latest`

Error: Newly-taken snapshot does not match reference.

**Comment by denisenepraunig** [comment]
@Shahzaib31 I experiences something similar. When running them locally - did you run them via Xcode or `xcodebuild`

When running the tests 
* locally via `xcodebuild` (failing) ❌
* running inside Xcode `Product -> Test`  (green) ✅
* on the CI (GitHub Actions) with `xcodebuilt` (failing) ❌

There weren't always the same tests failing and not all, but quite some tests...

**Comment by Nikoloutsos** [comment]
I use fastlane and it works like a charm

**Comment by stephencelis** [comment]
> `OS=latest`

Is the OS different on your machine vs. CI? Can you check the logs to see?

**Comment by mchirino89** [comment]
Is this issue still open?

**Comment by stephencelis** [comment]
@Shahzaib31 I'm going to close this issue since it appears like you resolved things. Let us know if you're still having issues, though!
