### ISSUE TITLE
Convert Data in snapshot to readable format

### ISSUE THREAD

**Issue by mcat345** [pointfreeco/swift-snapshot-testing#50]
▿ httpBody: Optional<Data>
    ▿ some: 175 bytes
      - count: 175
      ▿ pointer: 0x0000604000175610
        - pointerValue: 105827995702800

should be actually: - httpBody: "comments=string&phone=string&type=string"

**Comment by stephencelis** [comment]
Thanks for the report! Do you have code demonstrating use? We can't assume that `Data` always contains a UTF-8 string, unfortunately, but we do try to add special snapshot formats where we can. For www.pointfree.co we have a snapshot format for URLRequest which transforms bodies to strings when the content-type is right.

**Comment by stephencelis** [comment]
Gonna close this since I think there are workarounds, but feel free to reopen if you have more comments!
