### ISSUE TITLE
Build with added library fails during linking

### ISSUE THREAD

**Issue by morstin** [pointfreeco/swift-snapshot-testing#518]
Error in Linker:

Undefined symbol: static (extension in XCTest):__C.XCTContext.runActivity<A>(named: Swift.String, block: (__C.XCTActivity) throws -> A) throws -> A

**Comment by morstin** [comment]
I could solve the linking issue by setting "Enable Testing Search Paths" in Build Options of the project to "Yes". No idea what side-effects this might have, but so far it works.

**Comment by maurovz** [comment]
It "fixed" the issue but the app instantly crash afterwards for me.
