### ISSUE TITLE
Provide option to disable auto-recording on missing files

### ISSUE THREAD

**Issue by hebdavepaul0** [pointfreeco/swift-snapshot-testing#530]
When using various retry scenarios on CI/CD it can be possible for a test run to auto-record a missing snapshot, and then for a subsequent run to pass on that new snapshot.

We could provide a global boolean ( similar to isRecording ) in order to enable / disable auto-record functionality.

The default value would be true so existing integrations would not be affected.

It would be up to the client test target to determine how to best toggle the boolean based on their use case.

**Comment by hebdavepaul0** [comment]
implementation should be pretty straightforward, I should have a PR up by tomorrow morning at the latest.

**Comment by hebdavepaul0** [comment]
PR at https://github.com/pointfreeco/swift-snapshot-testing/pull/531

**Comment by stephencelis** [comment]
Thanks for the PR! I'll close this issue as a dupe so it can be tracked with the PR, instead.
