### ISSUE TITLE
We got an error "failed - Snapshot does not match reference." when we run the tests on different simulators

### ISSUE THREAD

**Issue by dlansakara** [pointfreeco/swift-snapshot-testing#545]
When we run the snapshot tests on a simulator which is different to the one we used to generate the baseline , tests are failing with the following error message:"failed - Snapshot does not match reference." Is this expected ? Are we suppose to run the tests on the same simulator (the one we used to generate the baseline) ?

**Comment by maxheld** [comment]
@dlansakara I would recommend deciding on a 'reference device' which is a simulator and a specific OS version. Some OS versions render the same colours differently for some reason

**Comment by stephencelis** [comment]
This is to be expected. From the README:

> ⚠️ Warning: Snapshots must be compared using a simulator with the same OS, device gamut, and scale as the simulator that originally took the reference to avoid discrepancies between images.

As such, always run snapshot tests on a consistent simulator.
