### ISSUE TITLE
Add additional method to add XCResult attachments

### ISSUE THREAD

**Issue by mattrobmattrob** [pointfreeco/swift-snapshot-testing#549]
Add an additional env variable aside from `__XCODE_BUILT_PRODUCTS_DIR_PATHS` to tell `SnapshotTesting` to write XCResult attachments. This could simplistically be just another environment variable (let's say `SNAPSHOT_TESTING_WRITE_ATTACHMENTS`) that test environments can set to write the attachments.

https://github.com/pointfreeco/swift-snapshot-testing/blob/0259c2fbd69c7bfaa34b0b86280496f84653e396/Sources/SnapshotTesting/AssertSnapshot.swift#L279-L285

This is useful in the context of Bazel where the test runner is custom but avoids setting the `__XCODE_BUILT_PRODUCTS_DIR_PATHS` env var which could cause some unintended consequences when set by something other than Xcode.

**Comment by stephencelis** [comment]
Hey @mattrobmattrob! Thanks for filing this issue and opening the associated PR. For the moment I'm going to close this issue in favor of tracking it in the PR, instead.
