### ISSUE TITLE
Running test repeatedly results in duplicate snapshot being created.

### ISSUE THREAD

**Issue by Deco354** [pointfreeco/swift-snapshot-testing#577]
**Describe the bug**
Running a snapshot test repeatedly with xcode's new 'run test repeatedly' functionality results in additional snapshots being created for that test.

We've a wrapper around this library which I've posted below although the identifier we're passing in to the testName does not include the iteration number at the real testSnapshot callsite.

```swift
    public func testSnapshot(_ view: UIView,
                             identifier: String = #function,
                             snapshotType: SnapshotType = .image,
                             precision: CGFloat = 0.95,
                             file: StaticString = #file,
                             line: UInt = #line,
                             waiting: TimeInterval = 0,
                             isArchitectureDependent: Bool = false) {
        semaphore.wait()
        var testID = identifier
        if isArchitectureDependent && (Architecture.isArm64 || Architecture.isRosettaEmulated) {
            testID.append("-arm64")
        }
        
        switch snapshotType {
        case .image:
            assertSnapshot(matching: view,
                           as: .wait(for: waiting, on: .image(precision: Float(precision))),
                           record: isRecording,
                           file: file,
                           testName: testID,
                           line: line)
            
        case .recursiveDescription:
            assertSnapshot(matching: view,
                           as: .wait(for: waiting, on: .recursiveDescription()),
                           record: isRecording,
                           file: file,
                           testName: testID,
                           line: line)
        }
        semaphore.signal()
    }
```

**To Reproduce**
Take any snapshot test right click on it and run "test <test name> repeatedly". At a certain iteration a number matching this iteration (2 in the screenshots below) will be appended to the snapshot reference image name causing an additional snapshot to be saved and the tests to fail.
![image](https://user-images.githubusercontent.com/18557720/155146847-79192f48-414b-4f37-9927-1262bf63608c.png)

![image](https://user-images.githubusercontent.com/18557720/155147972-6a87820f-7598-4188-a82a-57cf231c5250.png)

**Expected behavior**
I'd expect the test to use only one snapshot no matter how many time they're run.

**Environment**
  - swift-snapshot-testing version [e.g. 1.8.1]
  - Xcode 13.2
  - Swift 5.5
  - OS: iOS 15

**Comment by simondelphia** [comment]
A workaround is to set the `named` parameter

**Comment by Deco354** [comment]
@stephencelis Can we reopen this? Using the named parameter is a work-around rather than a fix. It won't be immediately obvious to anyone other than those within this thread.

**Comment by Deco354** [comment]
Sorry I must have skimmed this thread and missed #585 completely.
Thanks for getting this merged and thanks @krzysztofpawski for taking the time to fix this 🍾
