### ISSUE TITLE
Avoid automatic recording if the snapshot is not present (use case: test retry)

### ISSUE THREAD

**Issue by broomburgo** [pointfreeco/swift-snapshot-testing#624]
I'd like to avoid automatic recording if the snapshot is not present. The use case, on my side, is the following:

- I give explicit names to snapshots;
- I enabled the test retry in the test plan.

The result is that, if some snapshots are missing, tests will actually pass because the first pass will record the snapshot, and the second will compare the new snapshot with the one that was just produced. But I'd prefer if the tests failed, so it there was the option, I'd disable the automatic recording. Is it possible?

Thanks

**Comment by markst** [comment]
Isn't this a dupe of #530?

**Comment by broomburgo** [comment]
I'm closing this. It's already tracked in https://github.com/pointfreeco/swift-snapshot-testing/pull/531
