### ISSUE TITLE
Blur is rendered with straight edges

### ISSUE THREAD

**Issue by DanKorkelia** [pointfreeco/swift-snapshot-testing#682]
Anyone has this issue with snapshot tests. When running a test on a view that has a blur modifier. The blur is rendered with straight edges?

For example this view below.

        var sut: some View {
            Circle()
                .background(Color.red)
                .foregroundColor(.white)
                .blur(radius:  100)
        }

**Comment by hiragram** [comment]
I also have the same problem.

**Comment by DanKorkelia** [comment]
Closed issues due to inactivity.
