### ISSUE TITLE
1.10.0 contains breaking API changes

### ISSUE THREAD

**Issue by carlos4242** [pointfreeco/swift-snapshot-testing#697]
**Describe the bug**
iOS 12 support was dropped in 1.10.0. This broke our package build and will probably break other people's SPM package builds. Our dependency was imported using the recommended form `.package(url: "https://github.com/pointfreeco/swift-snapshot-testing.git", from: "1.9.0")` and most people will use this form, it allows automatic update to any new *minor* version. Our package specifies `platforms: [.iOS(.v12)],` for this package.

**To Reproduce**
Any SPM package that specifies a minimum iOS version of 12.

**Expected behavior**
Either 1.10 should be altered to restore support for iOS 12, or it should be changed to version 2.0.0. In future please always follow semantic versioning guidelines *exactly*, because Swift SPM expects this and works on this basis, or you will keep breaking people's builds. Thank you.

**Environment**
  - swift-snapshot-testing version 1.x.0
  - Xcode 14.1
  - Swift 5.5
  - OS: any

**Comment by stephencelis** [comment]
Just released 1.11.0, which restores the previous requirements. Sorry about that!

**Comment by carlos4242** [comment]
Fantastic work!! Thanks!
