### ISSUE TITLE
1.11.0 release "full changelog" tag mismatch

### ISSUE THREAD

**Issue by simondelphia** [pointfreeco/swift-snapshot-testing#699]
Says 1.10.1 at the bottom "full changelog", 1.11.0 at the top? Just a small typo I think.

![image](https://user-images.githubusercontent.com/69437320/213811969-3c6eb2aa-cf8e-4049-af2f-eb0aee1a4862.png)

https://github.com/pointfreeco/swift-snapshot-testing/releases/tag/1.11.0

the tag "1.10.1" does not exist

**Comment by stephencelis** [comment]
@simondelphia That is just a typo in the release notes. Was going to do a patch release but after reviewing the logs a minor seemed more appropriate. Updated the notes, thanks!
