### ISSUE TITLE
[Question] Rearchitect to not require subclassing SnapshotTestCase?

### ISSUE THREAD

**Issue by Killectro** [pointfreeco/swift-snapshot-testing#71]
We use [Quick](https://github.com/Quick/Quick) for testing and are therefore required to subclass `QuickSpec`, which precludes us from also subclassing `SnapshotTestCase`. Is it possible to architect this as a set of extensions to `XCTestCase` so that it can be used alongside other testing libraries that are less flexible?

I would be happy to put some work into this and put up a PR if you think it would be possible/valuable.

**Comment by stephencelis** [comment]
Dang, we had that in the original design but had some flakiness with global state and recording snapshots. We'll have to investigate. Artsy has some open source stuff using Quick/Nimble and FBSnapshotTestCase, so I wonder how they handle it.

**Comment by Killectro** [comment]
I'm not deeply familiar with their architecture but from the bit of digging I've done it looks like they use extensions on `XCTestCase` and/or free functions for most of their code as well as a few auxiliary types for other purposes. 

There is a little bit of Obj-C in there as well that tracks the currently running test case, which might have something to do with how they address flakiness?
