### ISSUE TITLE
Explore failing based off snapshot state

### ISSUE THREAD

**Issue by stephencelis** [pointfreeco/swift-snapshot-testing#72]
We could explore how performance tests and snapshot tests are alike: performance tests are just snapshot tests of how fast a test should take. In this way, `.image(precision: 0.9)` is similar in how it allows for a certain amount of variation before failing.

One idea, for example, is to define a strategy like `.viewHierarchyDepth`, which could snap merely an image of how complicated a view's hierarchy is. On repeat runs, if the view hierarchy gets deeper, it'll fail.

**Comment by stephencelis** [comment]
Closing this. Fun idea but no need to clog issues.

**Comment by acecilia** [comment]
This is a great idea! Would be awesome to add support for this in the library, as there does not seem to be any good alternative out there
