### ISSUE TITLE
Cannot use Snapshot Testing in Xcode 15

### ISSUE THREAD

**Issue by fluecke** [pointfreeco/swift-snapshot-testing#744]
**Describe the bug**
When using Snapshot Testing in Xcode 15b2, errors occur in Snapshot Testing's extension of `NSBezierPath`, stating `curveTo` is only available on macOS 11 and later.

**To Reproduce**
Use Snapshot Testing in Xcode 15b2.

**Expected behavior**
Tests should still build.

**Screenshots**
![Screenshot 2023-06-28 at 14 41 21](https://github.com/pointfreeco/swift-snapshot-testing/assets/742719/84c0aa0a-054d-4cb0-ada1-ee13f8e6ae02)

**Environment**
  - swift-snapshot-testing version 1.11.0
  - Xcode 15b2
  - Swift 5.9
  - OS: macOS 13.4

**Additional context**
I assume this is because of faulty ` @available(iOS 11.0, *)` annotations. Since `NSBezierPath.swift` is only used on macOS this annotation does not have any effect there. I will gladly fix this and open a PR if this is not intentional.

**Comment by maximkrouk** [comment]
Same issue

**Comment by fluecke** [comment]
Sorry, there must have been something wrong on my end. This is obviously already fixed with [dc46eeb](https://github.com/pointfreeco/swift-snapshot-testing/commit/dc46eeb3928a75390651fac6c1ef7f93ad59a73b)

**Comment by maximkrouk** [comment]
@fluecke Yeah, seems like it was fixed in [dc46eeb](https://github.com/pointfreeco/swift-snapshot-testing/commit/dc46eeb3928a75390651fac6c1ef7f93ad59a73b), but there is no release yet, so the problem is not on your end, guys should release `1.11.1` 🌚

**Comment by stephencelis** [comment]
@maximkrouk Done, sorry for the delay!

**Comment by PaulDoesDev** [comment]
Cheers. I can go back to Xcode 15 now 😅

**Comment by fluecke** [comment]
@stephencelis no worries, thanks for your work!
