### ISSUE TITLE
[Request] Avoid automatically recording snapshots on CI

### ISSUE THREAD

**Issue by NachoSoto** [pointfreeco/swift-snapshot-testing#748]
I'm experimenting with moving to Xcode Cloud, and noticed that for some reason it's not finding the snapshots even though they're in the repo.
Because we have test retries enabled, I almost didn't see this, because the second try for every test passed:
<img width="860" alt="Screenshot 2023-07-20 at 13 02 36" src="https://github.com/pointfreeco/swift-snapshot-testing/assets/685609/8c1cf2ed-00fd-4ae8-a149-705effe5a703">

It occurs to me that it should be able to disable this behavior when running tests on CI, because the subsequent test run will always be a pass. If there is no snapshot when running tests on CI, it shouldn't try to create them.

Bonus points if there's an environment variable that the library can detect to automatically enable that setting in Xcode Cloud / CircleCI, etc.

**Comment by NachoSoto** [comment]
I just discovered https://github.com/pointfreeco/swift-snapshot-testing/discussions/553
I understand there's nothing that this framework can do to make that automatic, but at least I think it would be nice to make the issue more obvious. If I hadn't noticed the retries I wouldn't have noticed that this was broken.

**Comment by alexanderkhitev** [comment]
Hey guys! Any news/updates? Thanks

**Comment by Smponias** [comment]
Any Updates?
