### ISSUE TITLE
Enhancements to `diffTool`?

### ISSUE THREAD

**Issue by JackYoustra** [pointfreeco/swift-snapshot-testing#780]
My current workflow for image snapshot tests is usually imagemagik's compare tool, so I'll have a command like
```
compare "1.png" "2.png" png:- | open -a Preview.app -f
```

Unfortunately, the framework only lets me specify the "compare" step instead of providing the rest of the command. I was thinking on changing / adding a closure version of `diffTool` that'd be able to do this. Is there any interest in this or any ideas on how people would like a more generalized `diffTool`?

**Comment by tisohjung** [comment]
I would appreciate it if anyone can review this PR

https://github.com/pointfreeco/swift-snapshot-testing/pull/668

**Comment by endanke** [comment]
@JackYoustra you can probably make an alias to your command which would take the two parameters and run the whole thing.
