### ISSUE TITLE
`diffTool` have a Swift 6 warning on Xcode 15.3 with Strict Concurrency Checking set to Complete

### ISSUE THREAD

**Issue by diogot** [pointfreeco/swift-snapshot-testing#845]
**Describe the bug**

On Xcode 15.3 there is new warning in `diffTool` string:

![Screenshot 2024-04-08 at 08 53 29](https://github.com/pointfreeco/swift-snapshot-testing/assets/885516/4b562f9b-93a4-439d-b860-8cbeeb86a188)

**To Reproduce**

- Open a project in Xcode 15.3
- Set Strict Concurrency Checking to Complete
- Compile the project

**Expected behavior**
The project compile without warnings

**Environment**
  - swift-snapshot-testing version 1.16.0
  - Xcode 15.4
  - Swift 5.10

**Comment by mbrandonw** [comment]
Hi @diogot, this warning only appears when compiling the library itself, not when using the library. We will update the library for Swift 6 in due time, but since this does not affect people using our library we do not see it as an issue.

**Comment by diogot** [comment]
Hi @mbrandonw, it does appear in the project if you set a diff tool, like we do.

To workaround it we had to import with the library with `@preconcurrency`.

**Comment by mbrandonw** [comment]
Ah yes, if you set the `diffTool` that could be a warning, but the screenshot above should not produce a warning. I believe there have been fixes in Xcode 16 beta 4 in this area.

Also, if you are up-to-date with the newest version of SnapshotTesting, then you can also use the `withSnapshotTesting` helper. There's more info in the [1.17 migration guide](https://swiftpackageindex.com/pointfreeco/swift-snapshot-testing/main/documentation/snapshottesting/migratingto1.17).

**Comment by diogot** [comment]
Thanks!
