### ISSUE TITLE
swift 6 build fails due to Snapshotting not conforming to sendable

### ISSUE THREAD

**Issue by doozMen** [pointfreeco/swift-snapshot-testing#877]
**Describe the bug**
When I put my package.swift in 6.0 version it no longer compiles and gives this error. I guess I could disable language mode 6.0 but have no clue how to do that in package.swift. 

But I was not expecting it not to compile as the readme states it works on 6.0???

<img width="1420" alt="Screenshot 2024-07-23 at 19 12 01" src="https://github.com/user-attachments/assets/c6f48494-4e58-4a84-b175-10ec6d18b920">

**To Reproduce**

swift-driver version: 1.111.2 Apple Swift version 6.0 (swiftlang-6.0.0.5.15 clang-1600.0.22.6)
Target: arm64-apple-macosx14.0

**Expected behavior**
As it supoers
**Screenshots**

**Environment**
  - swift-snapshot-testing version [1.17.2]
  - Xcode [16.0 Beta 3]
  - Swift [6.0]
  - OS: [macosx14.0]

**Additional context**
Will try to make pr to fix it

**Comment by stephencelis** [comment]
@doozMen Are you using SnapshotTesting via SPM? Your language mode should be independent of a dependency, so these errors sound like bugs. Wanna share a project that reproduces the problem?

**Comment by doozMen** [comment]
Yes they due sound like bugs not related to snapshot testing and I have them in 1 project and not the other. So I guess I should create bug in swift 6 but as it is in beta I'm hesitant. I enjoy using it in other swift 6 project so will close this issue here as I think you are write and it is a bug. Thanks for the quick reply!
