### ISSUE TITLE
Update swift-syntax dependency's package url to https://github.com/swiftlang/swift-syntax

### ISSUE THREAD

**Issue by seankit** [pointfreeco/swift-snapshot-testing#878]
**Describe the bug**

It was announced at WWDC that the Swift project would be moving GitHub organizations, from `apple` to `swiftlang`. They wrote about it in some detail on [this blog post](https://www.swift.org/blog/swiftlang-github/
). It looks like swift-syntax recently completed the migration, and as such the url has changed to `https://github.com/swiftlang/swift-syntax`. 

If a Swift Package has both swift-syntax and swift-snapshot-testing as dependencies, this build warning is given:

>'swift-snapshot-testing' dependency on 'https://github.com/apple/swift-syntax' conflicts with dependency on 'https://github.com/swiftlang/swift-syntax' which has the same identity 'swift-syntax'. this will be escalated to an error in future versions of SwiftPM.

**To Reproduce**
[Demonstration.zip](https://github.com/user-attachments/files/16366875/Demonstration.zip)

**Expected behavior**
Swift Package should build without a conflicting identity warning.

**Screenshots**
N/A

**Environment**
  - swift-snapshot-testing version [e.g. 1.16.0]
  - Xcode [e.g. 15.4.0]
  - Swift [e.g. 5.10]
  - OS: [e.g. .iOS(.v15), .macOS(.v13) ]

**Additional context**
N/A

**Comment by stephencelis** [comment]
@seankit This rolled out in https://github.com/pointfreeco/swift-snapshot-testing/releases/tag/1.17.2

**Comment by seankit** [comment]
whoops I missed that somehow, thank you!
