### ISSUE TITLE
Add a curl snapshot strategy for URLRequest

### ISSUE THREAD

**Issue by mbrandonw** [pointfreeco/swift-snapshot-testing#88]

**Comment by Sherlouk** [comment]
https://github.com/Alamofire/Alamofire/blob/master/Source/Request.swift#L624-L697

Alamofire's curlRepresentation is here 😄

I'm happy to draft a PR using this/a similar solution, if that's something you'd be interested in?

**Comment by stephencelis** [comment]
Sounds great! We'd happily take a PR 👍
