### ISSUE TITLE
Xcode 16 Beta 5 - Cannot find type 'CustomExecutionTrait' in scope

### ISSUE THREAD

**Issue by lucasecf** [pointfreeco/swift-snapshot-testing#886]
**Describe the bug**

`swift-snapshot-testing` doesn't build anymore in the just released Xcode beta 5. Everything was fine up to the beta 4 build, so this is something new that this new version introduced I guess.

The error says `Cannot find type 'CustomExecutionTrait' in scope` - not sure if this type was just removed or the file using it needs a `import` something. Could not find any information about it in the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes).

The line causing the build error is this one: https://github.com/pointfreeco/swift-snapshot-testing/blob/e883fc9ea51e76dc9ed13fd4a92b0ee258a1e8c9/Sources/SnapshotTesting/SnapshotsTestTrait.swift#L35

Cannot really tell if this is a problem that will be only on this beta version or an "expected change" that will be propagated up to the release version.

**To Reproduce**

Just try to build `swift-snapshot-testing` on a test module using [Xcode beta build 5](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_16_beta_5/Xcode_16_beta_5.xip)

**Expected behavior**

The package builds properly on the latest Xcode

**Screenshots**

![Screenshot 2024-08-07 at 10 52 21](https://github.com/user-attachments/assets/ea88806f-7e76-4a84-bfa6-73f6b19b637c)

**Environment**

  - swift-snapshot-testing version  `1.17.3` (latest so far)
  - Xcode version 16.0 beta 5 (16A5221g)

**Comment by robinhayward** [comment]
I'm also seeing this issue

**Comment by lucasecf** [comment]
I'm closing this issue because it was actually fixed in the newly released version 1.17.4

https://github.com/pointfreeco/swift-snapshot-testing/pull/885

**Comment by mbrandonw** [comment]
Ah yes, thanks for cleaning this up for us @lucasecf!
