### ISSUE TITLE
Crash `Current context must not be nil` with swift-testing

### ISSUE THREAD

**Issue by jcubit** [pointfreeco/swift-snapshot-testing#915]
**Describe the bug**
I am running into an uncaught exception “Terminating app due to uncaught exception `NSInternalInconsistencyException`, reason: `Current context must not be nil`” when snapshot testing a string. _The problem only occurs when the test fails_. There is no problem at all when recording.

This is not an async test.

**To Reproduce**

Fresh new project

```swift
import Testing
import SnapshotTesting

struct SomeTests {
    @Test
    func this_test_crashes_when_assertion_fails() throws {
        withSnapshotTesting {
            assertSnapshot(of: "foo", as: .lines)
        }
    }
}
```

**Expected behavior**
Maybe I am missing something fundamental in the new snapshottesting setup, but this should not crash and I should get a diff in Xcode.

**Screenshots**
Similar screenshot as in #875 

**Environment**
  - swift-snapshot-testing version 1.17.5
  - Xcode 16.0 (16A242d)
  - Swift 6.0
  - OS: macOS 15.0.1 (24A348)

**Additional context**
This is not an async test, so #822 and #875 solutions do not apply here

Thank you in advance for looking into this!

**Comment by mbrandonw** [comment]
Hi @jcubit, thanks for the report! There's definitely something to fix here, and not sure how we missed it. There's a chance something changed between the Xcode 16 beta and final release. But either way, #916 will fix it.

**Comment by jcubit** [comment]
Thank you for your quick answer (and for this Package)! 🙏
