### ISSUE TITLE
Switch diffing algorithm to use patience

### ISSUE THREAD

**Issue by stephencelis** [pointfreeco/swift-snapshot-testing#95]
Patience is more human-readable.

**Comment by digoreis** [comment]
Hi guys, I'm starting to try to implement this algorithm in Swift. The result is human-readable but the algorithm isn't readable 😄 . Is open yet this issue?

**Comment by stephencelis** [comment]
Definitely open to start tracking in a PR if you'd like to submit one! We can all try cleaning up the code together.

**Comment by digoreis** [comment]
Ah ok, I will try to finish the patience implementation this week and transform in a Diff strategy. 

I'm using this article: https://blog.jcoglan.com/2017/09/28/implementing-patience-diff/

My implementation V1: https://gist.github.com/digoreis/9254a292b3da2e97eb75f0afc3b384ef

**Comment by stephencelis** [comment]
This looks like a great start! Would you be interested in opening a PR to incorporate it into SnapshotTesting so that we can try it out?

**Comment by stephencelis** [comment]
Hi @digoreis! Just wanted to follow up here. I'm going to close this issue but would still love to see a PR in the future if you decide to take it on :smile:
