### ISSUE TITLE
`#if Xcode` compiler directive

### ISSUE THREAD

**Issue by mluisbrown** [pointfreeco/swift-snapshot-testing#99]
I was integrating this into a project via Cocoapods and noticed that all the code between the `#if Xcode` directives wasn't being compiled. Where is this defined? I'm using Xcode, of course 😄 

I worked around this by adding `-D Xcode` to `OTHER_SWIFT_FLAGS` for the library via a Podfile `post_install` hook.

**Comment by stephencelis** [comment]
Huh! I swore this check worked, so maybe it's a SwiftPM-only directive. It's definitely broken for everyone now, though, since we switched over to XcodeGen recently. Guess we didn't notice because we don't really use the XCTAttachment viewer 😅

**Comment by mluisbrown** [comment]
Thanks for fixing this so quickly @stephencelis 👍
